Cataclysm BN: achievement Class Reference
achievement Class Reference
#include <achievement.h>
Classes
class time_bound
Public Member Functions
achievement ()=default
void load (const JsonObject &, const std::string &)
void check () const
std::string ui_text () const
const translation & name () const
const translation & description () const
const std::vector< string_id< achievement > > & hidden_by () const
const std::optional< time_bound > & time_constraint () const
const std::map< skill_id, std::pair< achievement_comparison, int > > & skill_requirements () const
const std::vector< achievement_requirement > & requirements () const
Static Public Member Functions
static void load_achievement (const JsonObject &, const std::string &)
static void finalize ()
static void check_consistency ()
static const std::vector< achievement > & get_all ()
static void reset ()
Public Attributes
string_id< achievement > id
bool was_loaded = false
Private Member Functions
void add_skill_requirements (const JsonObject &jo, const std::string &src)
Retrieves skill requirement JsonObjects and feeds it to add_skill_requirement.
void add_skill_requirement (const JsonObject inner, const std::string &src)
Organizes variables provided and adds skill_requirements to achievements.
Private Attributes
translation name_
translation description_
std::vector< string_id< achievement > > hidden_by_
std::optional< time_bound > time_constraint_
std::map< skill_id, std::pair< achievement_comparison, int > > skill_requirements_
std::vector< achievement_requirement > requirements_
Detailed Description
Definition at line 56 of file achievement.h.
Constructor & Destructor Documentation
achievement()
achievement::achievement () default
Member Function Documentation
add_skill_requirement()
void achievement::add_skill_requirement (const JsonObject inner, const std::string & src) private
Organizes variables provided and adds skill_requirements to achievements.
Definition at line 228 of file achievement.cpp.
{
    const skill_id skill = static_cast<skill_id>( inner.get_string( "skill" ) );
    const achievement_comparison compare = inner.get_enum_value<achievement_comparison>( "is" );
    const int count = inner.get_int( "level" );
    skill_requirements_[skill] = std::make_pair( compare, count );
}
References game_menus::inv::compare(), detail::count(), JsonObject::get_enum_value(), JsonObject::get_int(), JsonObject::get_string(), and skill_requirements_.
Referenced by add_skill_requirements().
add_skill_requirements()
void achievement::add_skill_requirements (const JsonObject & jo, const std::string & src) private
Retrieves skill requirement JsonObjects and feeds it to add_skill_requirement.
Definition at line 213 of file achievement.cpp.
{
    if( !jo.has_array( "skill_requirements" ) ) {
        return;
    }
    for( const JsonValue entry : jo.get_array( "skill_requirements" ) ) {
        if( entry.test_object() ) {
            add_skill_requirement( entry, src );
        } else {
            entry.throw_error( "array element is not an object." );
        }
    }
}
References add_skill_requirement(), JsonObject::get_array(), and JsonObject::has_array().
Referenced by load().
check()
void achievement::check () const
Definition at line 435 of file achievement.cpp.
{
    for( const string_id<achievement> &a : hidden_by_ ) {
        if( !a.is_valid() ) {
            debugmsg( "Achievement %s specifies hidden_by achievement %s, but the latter does not "
                      "exist.", id.str(), a.str() );
        }
    }
    if( time_constraint_ ) {
        time_constraint_->check( id );
    }
    if( !skill_requirements_.empty() ) {
        for( const auto& [sk_id, pair] : skill_requirements_ ) {
            auto &&[comp, level] = pair;
            if( !sk_id.is_valid() ) {
                debugmsg( "Achievement %s specifies invalid skill requirement %s", id.str(), sk_id.c_str() );
            } else if( comp == achievement_comparison::last ) {
                debugmsg( "Achievement %s specifies invalid comparator for skill requirement %s", id.str(),
                          sk_id.c_str() );
            } else if( level < 0 ) {
                debugmsg( "Achievement %s has negative value for skill requirement %s.", id.str(), sk_id.c_str() );
            }
        }
    }
    for( const achievement_requirement &req : requirements_ ) {
        req.check( id );
    }
}
References a, debugmsg, hidden_by_, last, requirements_, skill_requirements_, and time_constraint_.
check_consistency()
void achievement::check_consistency () static
Definition at line 407 of file achievement.cpp.
{
    achievement_factory.check();
}
References anonymous_namespace{achievement.cpp}::achievement_factory.
Referenced by DynamicDataLoader::check_consistency().
description()
const translation & achievement::description () const inline
Definition at line 77 of file achievement.h.
{
            return description_;
        }
References description_.
Referenced by achievement_tracker::ui_text(), achievement_state::ui_text(), and achievements_tracker::ui_text_for().
finalize()
void achievement::finalize () static
Definition at line 398 of file achievement.cpp.
{
    for( achievement &a : const_cast<std::vector<achievement>&>( achievement::get_all() ) ) {
        for( achievement_requirement &req : a.requirements_ ) {
            req.finalize();
        }
    }
}
References a, achievement_requirement::finalize(), and get_all().
Referenced by DynamicDataLoader::finalize_loaded_data().
get_all()
const std::vector< achievement > & achievement::get_all () static
Definition at line 412 of file achievement.cpp.
{
    return achievement_factory.get_all();
}
References anonymous_namespace{achievement.cpp}::achievement_factory.
Referenced by finalize(), achievements_tracker::notify(), and achievements_tracker::valid_achievements().
hidden_by()
const std::vector< string_id< achievement > > & achievement::hidden_by () const inline
Definition at line 81 of file achievement.h.
{
            return hidden_by_;
        }
References hidden_by_.
Referenced by achievements_tracker::is_hidden().
load()
void achievement::load (const JsonObject & jo, const std::string & src)
Definition at line 422 of file achievement.cpp.
{
    mandatory( jo, was_loaded, "name", name_ );
    optional( jo, was_loaded, "description", description_ );
    optional( jo, was_loaded, "hidden_by", hidden_by_ );
    optional( jo, was_loaded, "time_constraint", time_constraint_ );
    mandatory( jo, was_loaded, "requirements", requirements_ );
    if( jo.has_member( "skill_requirements" ) ) {
        add_skill_requirements( jo, src );
    }
}
References add_skill_requirements(), description_, JsonObject::has_member(), hidden_by_, mandatory(), name_, optional(), requirements_, time_constraint_, and was_loaded.
load_achievement()
void achievement::load_achievement (const JsonObject & jo, const std::string & src) static
Definition at line 393 of file achievement.cpp.
{
    achievement_factory.load( jo, src );
}
References anonymous_namespace{achievement.cpp}::achievement_factory.
Referenced by DynamicDataLoader::initialize().
name()
const translation & achievement::name () const inline
Definition at line 73 of file achievement.h.
{
            return name_;
        }
References name_.
Referenced by achievement_tracker::ui_text(), and achievement_state::ui_text().
requirements()
const std::vector< achievement_requirement > & achievement::requirements () const inline
Definition at line 113 of file achievement.h.
{
            return requirements_;
        }
References requirements_.
Referenced by ui_text(), and achievement_state::ui_text().
reset()
void achievement::reset () static
Definition at line 417 of file achievement.cpp.
{
    achievement_factory.reset();
}
References anonymous_namespace{achievement.cpp}::achievement_factory.
Referenced by DynamicDataLoader::unload_data().
skill_requirements()
const std::map< skill_id, std::pair< achievement_comparison, int > > & achievement::skill_requirements () const inline
Definition at line 110 of file achievement.h.
{
            return skill_requirements_;
        }
References skill_requirements_.
Referenced by skill_req_completed(), ui_text(), achievement_tracker::ui_text(), and achievement_state::ui_text().
time_constraint()
const std::optional< time_bound > & achievement::time_constraint () const inline
Definition at line 107 of file achievement.h.
{
            return time_constraint_;
        }
References time_constraint_.
Referenced by time_req_completed(), ui_text(), achievement_tracker::ui_text(), and achievement_state::ui_text().
ui_text()
std::string achievement::ui_text () const
Definition at line 315 of file achievement.cpp.
{
    std::string requirements;
    if( time_constraint() ) {
        requirements += time_constraint()->time_ui_text( time_req_completed( *this ) ) + "\n";
    }
    Character &u = get_player_character();
    for( const auto& [sk_id, pair] : skill_requirements() ) {
        std::string cur_skill;
        auto& [comp, level] = pair;
        int sk_lvl = u.get_skill_level( sk_id );
        achievement_completion status = ach_compare( comp, level, sk_lvl ) ?
                                        achievement_completion::completed : achievement_completion::pending;
        nc_color c = color_from_completion( status );
        cur_skill += string_format( _( "Attain %s skill level of %i (%i/%i)." ),
                                    sk_id->name(), level, sk_lvl, level ) + "\n";
        requirements += colorize( cur_skill, c );
    }
    return requirements;
}
References _, ach_compare(), c, color_from_completion(), colorize(), completed, get_player_character(), Character::get_skill_level(), pending, requirements(), skill_requirements(), string_format(), time_constraint(), and time_req_completed().
Referenced by achievement_tracker::ui_text(), and achievement_state::ui_text().
Member Data Documentation
description_
translation achievement::description_ private
Definition at line 118 of file achievement.h.
Referenced by description(), and load().
hidden_by_
std::vector<string_id<achievement> > achievement::hidden_by_ private
Definition at line 119 of file achievement.h.
Referenced by check(), hidden_by(), and load().
id
string_id<achievement> achievement::id
Definition at line 70 of file achievement.h.
Referenced by achievements_tracker::is_hidden(), achievements_tracker::notify(), achievements_tracker::ui_text_for(), and achievements_tracker::valid_achievements().
name_
translation achievement::name_ private
Definition at line 117 of file achievement.h.
Referenced by load(), and name().
requirements_
std::vector<achievement_requirement> achievement::requirements_ private
Definition at line 122 of file achievement.h.
Referenced by check(), load(), and requirements().
skill_requirements_
std::map<skill_id, std::pair<achievement_comparison, int> > achievement::skill_requirements_ private
Definition at line 121 of file achievement.h.
Referenced by add_skill_requirement(), check(), and skill_requirements().
time_constraint_
std::optional<time_bound> achievement::time_constraint_ private
Definition at line 120 of file achievement.h.
Referenced by check(), load(), and time_constraint().
was_loaded
bool achievement::was_loaded = false
Definition at line 71 of file achievement.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/achievement.h
src/achievement.cpp