Cataclysm BN: achievement::time_bound Class Reference
achievement::time_bound Class Reference
#include <achievement.h>
Public Types
enum class epoch { cataclysm , game_start , last }
Public Member Functions
void deserialize (JsonIn &)
void check (const string_id< achievement > &) const
std::string time_ui_text (const achievement_completion) const
time_point target () const
achievement_comparison comparison () const
Private Attributes
achievement_comparison comparison_
epoch epoch_
time_duration period_
Friends
class achievement
Detailed Description
Definition at line 85 of file achievement.h.
Member Enumeration Documentation
epoch
enum class achievement::time_bound::epoch strong
Enumerator
cataclysm
game_start
last
Definition at line 89 of file achievement.h.
{
                    cataclysm,
                    game_start,
                    last
                };
Member Function Documentation
check()
void achievement::time_bound::check (const string_id< achievement > & id) const
Definition at line 205 of file achievement.cpp.
{
    if( comparison_ == achievement_comparison::anything ) {
        debugmsg( "Achievement %s has unconstrained \"anything\" time_constraint.  "
                  "Please change it to a consequential comparison.", id.str() );
    }
}
References anything, and debugmsg.
comparison()
achievement_comparison achievement::time_bound::comparison () const
Definition at line 310 of file achievement.cpp.
{
    return comparison_;
}
deserialize()
void achievement::time_bound::deserialize (JsonIn & jin)
Definition at line 195 of file achievement.cpp.
{
    const JsonObject &jo = jin.get_object();
    if( !( jo.read( "since", epoch_ ) &&
           jo.read( "is", comparison_ ) &&
           jo.read( "target", period_ ) ) ) {
        jo.throw_error( "Mandatory field missing for achievement time_constaint" );
    }
}
References comparison_, epoch_, JsonIn::get_object(), period_, JsonObject::read(), and JsonObject::throw_error().
target()
time_point achievement::time_bound::target () const
Definition at line 305 of file achievement.cpp.
{
    return epoch_to_time_point( epoch_ ) + period_;
}
References epoch_to_time_point().
time_ui_text()
std::string achievement::time_bound::time_ui_text (const achievement_completion comp) const
Definition at line 337 of file achievement.cpp.
{
    time_point now = calendar::turn;
    nc_color c = color_from_completion( comp );
    auto translate_epoch = []( epoch e ) {
        switch( e ) {
            case epoch::cataclysm:
                return _( "time of cataclysm" );
            case epoch::game_start:
                return _( "start of game" );
            case epoch::last:
                break;
        }
        debugmsg( "Invalid epoch" );
        abort();
    };
    std::string message = [&]() {
        switch( comp ) {
            case achievement_completion::pending:
                return string_format( _( "At least %s from %s (%s remaining)" ),
                                      to_string( period_ ), translate_epoch( epoch_ ),
                                      to_string( target() - now ) );
            case achievement_completion::completed:
                switch( comparison_ ) {
                    case achievement_comparison::less_equal:
                        return string_format( _( "Within %s of %s (%s remaining)" ),
                                              to_string( period_ ), translate_epoch( epoch_ ),
                                              to_string( target() - now ) );
                    case achievement_comparison::greater_equal:
                        return string_format( _( "At least %s from %s (passed)" ),
                                              to_string( period_ ), translate_epoch( epoch_ ) );
                    case achievement_comparison::anything:
                        return std::string();
                    case achievement_comparison::last:
                        break;
                }
                debugmsg( "Invalid achievement_comparison" );
                abort();
            case achievement_completion::failed:
                return string_format( _( "Within %s of %s (passed)" ),
                                      to_string( period_ ), translate_epoch( epoch_ ) );
            case achievement_completion::last:
                break;
        }
        debugmsg( "Invalid achievement_completion" );
        abort();
    }
    ();
    return colorize( message, c );
}
References _, abort, anything, c, color_from_completion(), colorize(), completed, debugmsg, failed, greater_equal, last, less_equal, mapgen_defer::message, pending, string_format(), to_string(), and calendar::turn.
Friends And Related Function Documentation
achievement
friend class achievement friend
Definition at line 88 of file achievement.h.
Member Data Documentation
comparison_
achievement_comparison achievement::time_bound::comparison_ private
Definition at line 102 of file achievement.h.
Referenced by deserialize().
epoch_
epoch achievement::time_bound::epoch_ private
Definition at line 103 of file achievement.h.
Referenced by deserialize().
period_
time_duration achievement::time_bound::period_ private
Definition at line 104 of file achievement.h.
Referenced by deserialize().
The documentation for this class was generated from the following files:
src/achievement.h
src/achievement.cpp