Cataclysm BN: src/map.cpp File Reference
map.cpp File Reference
#include "map.h"
#include <algorithm>
#include <array>
#include <cassert>
#include <climits>
#include <cstdlib>
#include <cstring>
#include <limits>
#include <optional>
#include <ostream>
#include <queue>
#include <type_traits>
#include <unordered_map>
#include "active_item_cache.h"
#include "ammo.h"
#include "ammo_effect.h"
#include "artifact.h"
#include "avatar.h"
#include "basecamp.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_utility.h"
#include "character.h"
#include "character_id.h"
#include "clzones.h"
#include "colony.h"
#include "color.h"
#include "construction.h"
#include "coordinate_conversions.h"
#include "creature.h"
#include "cursesdef.h"
#include "damage.h"
#include "debug.h"
#include "distribution_grid.h"
#include "drawing_primitives.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "explosion.h"
#include "field.h"
#include "field_type.h"
#include "flat_set.h"
#include "fragment_cloud.h"
#include "fungal_effects.h"
#include "game.h"
#include "harvest.h"
#include "iexamine.h"
#include "input.h"
#include "int_id.h"
#include "item.h"
#include "item_contents.h"
#include "item_factory.h"
#include "item_group.h"
#include "item_location.h"
#include "itype.h"
#include "iuse.h"
#include "iuse_actor.h"
#include "lightmap.h"
#include "line.h"
#include "map_functions.h"
#include "map_iterator.h"
#include "map_memory.h"
#include "map_selector.h"
#include "mapbuffer.h"
#include "math_defines.h"
#include "memory_fast.h"
#include "messages.h"
#include "mongroup.h"
#include "monster.h"
#include "morale_types.h"
#include "mtype.h"
#include "npc.h"
#include "options.h"
#include "output.h"
#include "overmapbuffer.h"
#include "pathfinding.h"
#include "player.h"
#include "point_float.h"
#include "projectile.h"
#include "rng.h"
#include "safe_reference.h"
#include "scent_map.h"
#include "sounds.h"
#include "string_formatter.h"
#include "string_id.h"
#include "submap.h"
#include "tileray.h"
#include "timed_event.h"
#include "translations.h"
#include "trap.h"
#include "ui_manager.h"
#include "value_ptr.h"
#include "veh_type.h"
#include "vehicle.h"
#include "visitable.h"
#include "vpart_position.h"
#include "vpart_range.h"
#include "weather.h"
#include "weighted_list.h"
Macros
#define dbg(x) DebugLog((x),DC::Map)
Typedefs
using ammo_effect_str_id = string_id< ammo_effect >
Functions
static const std::string flag_RECHARGE ("RECHARGE")
static const std::string flag_USE_UPS ("USE_UPS")
static const std::string flag_USES_GRID_POWER ("USES_GRID_POWER")
map & get_map ()
static bool sees_veh (const Creature &c, vehicle &veh, bool force_recalc)
static bool will_explode_on_impact (const int power)
static bool furn_is_supported (const map &m, const tripoint &p)
static int get_sound_volume (const map_bash_info &bash)
static bool process_map_items (item_stack &items, safe_reference< item > &item_ref, const tripoint &location, const temperature_flag flag)
static void process_vehicle_items (vehicle &cur_veh, int part)
static temperature_flag temperature_flag_at_point (const map &m, const tripoint &p)
template<typename Stack >
std::list< item > use_amount_stack (Stack stack, const itype_id &type, int &quantity, const std::function< bool(const item &)> &filter)
template<typename Stack >
std::list< item > use_charges_from_stack (Stack stack, const itype_id &type, int &quantity, const tripoint &pos, const std::function< bool(const item &)> &filter)
static void use_charges_from_furn (const furn_t &f, const itype_id &type, int &quantity, map *m, const tripoint &p, std::list< item > &ret, const std::function< bool(const item &)> &filter)
static bool has_memory_at (const tripoint &p)
static int get_memory_at (const tripoint &p)
template<int SIZE, int MULTIPLIER>
void shift_bitset_cache (std::bitset< SIZE *SIZE > &cache, point s)
template void shift_bitset_cache< MAPSIZE_X, SEEX > (std::bitset< MAPSIZE_X *MAPSIZE_X > &cache, point s)
template void shift_bitset_cache< MAPSIZE, 1 > (std::bitset< MAPSIZE *MAPSIZE > &cache, point s)
static void shift_tripoint_set (std::set< tripoint > &set, point offset, const half_open_rectangle< point > &boundaries)
template<typename T >
static void shift_tripoint_map (std::map< tripoint, T > &map, point offset, const half_open_rectangle< point > &boundaries)
static void generate_uniform (const tripoint &p, const ter_id &terrain_type)
static void vehicle_caching_internal (level_cache &zch, const vpart_reference &vp, vehicle *v)
static void vehicle_caching_internal_above (level_cache &zch_above, const vpart_reference &vp, vehicle *v)
Variables
static const ammo_effect_str_id ammo_effect_INCENDIARY ("INCENDIARY")
static const ammo_effect_str_id ammo_effect_LASER ("LASER")
static const ammo_effect_str_id ammo_effect_LIGHTNING ("LIGHTNING")
static const ammo_effect_str_id ammo_effect_PLASMA ("PLASMA")
static const itype_id itype_autoclave ("autoclave")
static const itype_id itype_battery ("battery")
static const itype_id itype_chemistry_set ("chemistry_set")
static const itype_id itype_dehydrator ("dehydrator")
static const itype_id itype_electrolysis_kit ("electrolysis_kit")
static const itype_id itype_food_processor ("food_processor")
static const itype_id itype_forge ("forge")
static const itype_id itype_hotplate ("hotplate")
static const itype_id itype_kiln ("kiln")
static const itype_id itype_nail ("nail")
static const itype_id itype_press ("press")
static const itype_id itype_soldering_iron ("soldering_iron")
static const itype_id itype_vac_sealer ("vac_sealer")
static const itype_id itype_welder ("welder")
static const mtype_id mon_zombie ("mon_zombie")
static const skill_id skill_traps ("traps")
static const efftype_id effect_boomered ("boomered")
static const efftype_id effect_crushed ("crushed")
static const ter_str_id t_rock_floor_no_roof ("t_rock_floor_no_roof")
static cata::colony< item > nulitems
static field nulfield
static level_cache nullcache
bool disable_mapgen = false
Causes all generated maps to be empty grass and prevents saved maps from being loaded, used by the test suite.
static submap null_submap
Macro Definition Documentation
dbg
#define dbg (x) DebugLog((x),DC::Map)
Definition at line 139 of file map.cpp.
Typedef Documentation
ammo_effect_str_id
using ammo_effect_str_id = string_id<ammo_effect>
Definition at line 104 of file map.cpp.
Function Documentation
flag_RECHARGE()
static const std::string flag_RECHARGE ("RECHARGE") static
Referenced by process_vehicle_items().
flag_USE_UPS()
static const std::string flag_USE_UPS ("USE_UPS") static
Referenced by process_vehicle_items().
flag_USES_GRID_POWER()
static const std::string flag_USES_GRID_POWER ("USES_GRID_POWER") static
Referenced by use_charges_from_furn().
furn_is_supported()
static bool furn_is_supported (const map & m, const tripoint & p) static
Definition at line 3239 of file map.cpp.
{
    const signed char cx[4] = { 0, -1, 0, 1};
    const signed char cy[4] = { -1,  0, 1, 0};
    for( int i = 0; i < 4; i++ ) {
        const point adj( p.xy() + point( cx[i], cy[i] ) );
        if( m.has_furn( tripoint( adj, p.z ) ) &&
            m.furn( tripoint( adj, p.z ) ).obj().has_flag( "BLOCKSDOOR" ) ) {
            return true;
        }
    }
    return false;
}
References map::furn(), map_data_common_t::has_flag(), map::has_furn(), int_id< T >::obj(), tripoint::xy(), and tripoint::z.
Referenced by map::bash_ter_furn().
generate_uniform()
static void generate_uniform (const tripoint & p, const ter_id & terrain_type) static
Definition at line 7081 of file map.cpp.
{
    dbg( DL::Info ) << "generate_uniform p: " << p
                    << "  terrain_type: " << terrain_type.id().str();
    for( int xd = 0; xd <= 1; xd++ ) {
        for( int yd = 0; yd <= 1; yd++ ) {
            submap *sm = new submap();
            sm->is_uniform = true;
            sm->set_all_ter( terrain_type );
            sm->last_touched = calendar::turn;
            MAPBUFFER.add_submap( p + point( xd, yd ), sm );
        }
    }
}
References mapbuffer::add_submap(), dbg, int_id< T >::id(), Info, MAPBUFFER, coords::sm, string_id< T >::str(), and calendar::turn.
Referenced by map::loadn().
get_map()
map & get_map ()
Definition at line 147 of file map.cpp.
{
    return g->m;
}
Referenced by basecamp::abandon_camp(), Character::absorb_hit(), vehicle::act_on_map(), computer_session::action_blood_anal(), computer_session::action_cascade(), computer_session::action_conveyor(), computer_session::action_data_anal(), computer_session::action_deactivate_shock_vent(), computer_session::action_elevator_on(), computer_session::action_extract_rad_source(), computer_session::action_geiger(), computer_session::action_irradiator(), computer_session::action_list_bionics(), computer_session::action_lock(), computer_session::action_open(), computer_session::action_portal(), computer_session::action_release(), computer_session::action_release_bionics(), computer_session::action_sample(), computer_session::action_shutters(), computer_session::action_srcf_seal(), computer_session::action_terminate(), computer_session::action_unlock(), Character::activate_bionic(), enchantment::activate_passive(), activity_on_turn_move_loot(), zone_manager::add(), ter_furn_transform::add_all_messages(), add_basecamp_storage_to_loot_zone_list(), map::add_field(), explosion_handler::ExplosionProcess::add_field(), advanced_inventory_pane::add_items_from_area(), Character::add_known_trap(), vehicle::adjust_zlevel(), vehicle::advance_precalc_mounts(), iexamine::aggie_plant(), npc::alt_attack(), item::ammo_consume(), apply< furn_t >(), apply< ter_t >(), apply< trap >(), apply_ammo_effects(), apply_camp_ownership(), apply_lock_picking_tool(), apply_prying_tool(), iexamine::arcfurnace_empty(), iexamine::arcfurnace_full(), are_requirements_nearby(), npc::assess_danger(), assign_veh_to_follow(), Creature::auto_find_hostile_target(), iexamine::autoclave_full(), iexamine::autodoc(), iexamine::bars(), character_funcs::base_comfort_value(), talk_function::basecamp_mission(), spell_effect::bash(), explosion_handler::ExplosionProcess::blast_tile(), Creature::bleed(), Character::blossoms(), mattack::boomer(), mattack::boomer_glow(), activity_handlers::build_do_turn(), iexamine::bulletin_board(), Character::burn_fuel(), activity_handlers::burrow_finish(), butcher_corpse_activity(), activity_handlers::butcher_finish(), butchery_drops_harvest(), butchery_quarter(), zone_manager::cache_vzones(), leap_actor::call(), can_butcher_at(), can_construct(), can_do_activity_there(), can_examine_at(), iexamine::can_fertilize(), can_interact_at(), Character::can_mount(), npc::can_move_to(), can_move_vertical_at(), npc::can_open_door(), can_pickup_at(), monster::can_reach_to(), monster::can_squeeze_to(), defense_game::caravan(), iexamine::cardreader(), iexamine::cardreader_foodplace(), iexamine::cardreader_robofac(), iexamine::chainfence(), advanced_inventory::change_square(), construct::check_deconstruct(), vehicle::autodrive_controller::check_drivable(), player::check_eligible_containers_for_crafting(), construct::check_empty(), vehicle::check_falling_or_floating(), vehicle::check_heli_ascend(), vehicle::check_heli_descend(), deploy_tent_actor::check_intact(), vehicle::check_is_heli_landed(), construct::check_no_trap(), Character::check_outbounds_activity(), construct::check_ramp_high(), relic_funcs::check_recharge_reqs(), construct::check_support(), choose_adjacent(), choose_adjacent_highlight(), target_ui::choose_initial_target(), activity_handlers::chop_logs_finish(), chop_plank_activity(), activity_handlers::chop_planks_finish(), chop_tree_activity(), activity_handlers::chop_tree_do_turn(), activity_handlers::chop_tree_finish(), activity_handlers::churn_finish(), cleanup_tiles(), activity_handlers::clear_rubble_finish(), clear_shot_reach(), close(), talk_function::companion_return(), complete_construction(), veh_interact::complete_vehicle(), vehicle::autodrive_controller::compute_obstacles(), consider_butchery(), construction_activity(), basecamp_action_components::consume_components(), player::consume_items(), Character::consume_remote_fuel(), player::consume_tools(), iexamine::controls_gate(), npc::could_move_onto(), activity_handlers::cracking_finish(), spell::create_field(), fungal_effects::create_spores(), zone_manager::create_vehicle_loot_zone(), iexamine::curtains(), salvage_actor::cut_up(), cyborg_on_couch(), cycle_action(), vehicle::damage_direct(), monexamine::deactivate_pet(), debug_menu::debug(), iexamine::deployed_furniture(), item_location::impl::item_on_map::describe(), item_location::deserialize(), overmapbuffer::despawn_monster(), iuse::directional_antenna(), iexamine::dirtmound(), crafting::disassemble_all(), activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}::discharge_real_power_source(), displace_items_except_one_liquid(), basecamp::distribute_food(), character_funcs::do_pause(), npc::do_pulp(), aim_activity_actor::do_turn(), construct::done_deconstruct(), construct::done_digormine_stair(), construct::done_extract_maybe_revert_to_dirt(), construct::done_grave(), construct::done_mark_firewood(), construct::done_mark_practice_target(), construct::done_mine_upstair(), construct::done_ramp_high(), construct::done_ramp_low(), construct::done_vehicle(), construct::done_window_curtains(), construct::done_wood_stairs(), iexamine::door_peephole(), editmap_hilight::draw(), draw_health_classic(), anonymous_namespace{animation.cpp}::draw_line_curses(), editmap::draw_main_ui_overlay(), advanced_inventory::draw_minimap(), target_ui::draw_terrain_overlay(), draw_veh_compact(), draw_veh_padding(), Character::drop(), Character::drop_invalid_inventory(), npc::drop_items(), drop_on_map(), drop_or_embed_projectile(), talk_function::drop_stolen_item(), talk_function::drop_weapon(), monexamine::dump_items(), avatar_action::eat_here(), editmap::edit(), editmap::edit_fld(), editmap::edit_itm(), editmap::edit_mapgen(), editmap::edit_veh(), iexamine::egg_sack_generic(), iexamine::elevator(), explosion_handler::emp_blast(), enumerate_objects_around_point(), Character::env_surgery_bonus(), npc::execute_action(), ranged::execute_shaped_attack(), ranged::expected_coverage(), extract_or_wreck_cbms(), computer_session::failure_destroy_blood(), computer_session::failure_destroy_data(), computer_session::failure_manhacks(), computer_session::failure_pump_explode(), computer_session::failure_pump_leak(), computer_session::failure_secubots(), computer_session::failure_shutdown(), farm_action(), feature< furn_id >(), feature< ter_id >(), feature< trap_id >(), iexamine::fertilize_plant(), fetch_activity(), activity_handlers::fill_liquid_do_turn(), explosion_handler::ExplosionProcess::fill_maps(), activity_handlers::fill_pit_finish(), find_auto_consume(), find_base_construction(), find_best_fire(), find_closest_stair(), npc::find_corpse_to_pulp(), npc::find_dangerous_explosives(), npc::find_item(), find_refuel_spot_zone(), Character::find_remote_fuel(), find_target_vehicle(), character_funcs::fine_detail_vision_mod(), dig_activity_actor::finish(), dig_channel_activity_actor::finish(), disassemble_activity_actor::finish(), hacking_activity_actor::finish(), fire(), ranged::fire_gun(), iexamine::fireplace(), mattack::flame(), explosion_handler::explosion_funcs::flashbang(), Character::floor_bedding_warmth(), Character::floor_item_warmth(), iexamine::flower_cactus(), iexamine::flower_dahlia(), iexamine::flower_marloss(), iexamine::flower_poppy(), mdeath::focused_beam(), activity_handlers::forage_finish(), Character::forced_dismount(), basecamp::form_crafting_inventory(), advanced_inv_area::free_volume(), fromPumpFuel(), iexamine::fswitch(), iuse::fungicide(), mdeath::fungus(), iexamine::fungus(), iexamine::fvat_empty(), iexamine::fvat_full(), iexamine::gaspump(), generate_weather_anim_frame(), generic_multi_activity_check_requirement(), generic_multi_activity_do(), generic_multi_activity_handler(), generic_multi_activity_locations(), get_basecamp(), avatar::get_book_reader(), zone_manager::get_bottom_zone(), item::get_cable_target(), advanced_inv_area::get_container(), get_convection_temperature(), character_funcs::get_crafting_helpers(), player::get_eligible_containers_for_crafting(), activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}::get_fake_tool(), anonymous_namespace{gates.cpp}::get_gate_id(), get_hack_type(), get_heat_radiation(), advanced_inv_area::get_item_count(), get_item_location(), get_keg_capacity(), liquid_handler::get_liquid_target(), overmapbuffer::get_npcs_near_player(), overmap_ui::get_overmap_path_to(), zone_manager::get_point_set_loot(), player_activity::get_progress_message(), map_memory::get_submap(), ranged::get_weapon_dispersion(), zone_manager::get_zone_at(), get_zone_for_act(), zone_manager::get_zones(), iexamine::getGasPumpByNumber(), iexamine::getNearFilledGasTank(), getNearPumpCount(), Character::global_square_location(), vehicle::global_square_location(), npc::go_to_omt_destination(), npc::good_escape_direction(), good_fishing_spot(), grab(), npc::guard_current_pos(), activity_handlers::hacksaw_finish(), handbrake(), handle_action_menu(), handle_harvest(), liquid_handler::handle_liquid_from_ground(), npc::handle_sound(), vehicle::handle_trap(), harvest_common(), iexamine::harvest_furn(), iexamine::harvest_furn_nectar(), iexamine::harvest_plant(), iexamine::harvest_ter(), iexamine::harvest_ter_nectar(), Character::has_alarm_clock(), has_clear_path_to_pickup_items(), Character::has_destination_activity(), Character::has_fire(), has_neighbor(), has_pre_terrain(), Character::has_watch(), haul(), Character::heat_emission(), Character::i_add_or_drop(), Character::in_climate_control(), in_spell_aoe(), scent_map::inbounds(), talk_function::individual_mission(), advanced_inv_area::init(), vehicle::interact_with(), enchantment::is_active(), place_trap_actor::is_allowed(), Character::is_deaf(), is_driving(), explosion_handler::ExplosionProcess::is_occluded(), is_player_outside(), Character::is_snuggling(), is_solid_neighbor(), anonymous_namespace{gates.cpp}::gate_data::is_suitable_wall(), ma_requirements::is_valid_character(), behavior::monster_oracle_t::items_available(), activity_handlers::jackhammer_do_turn(), activity_handlers::jackhammer_finish(), iexamine::keg(), iexamine::kiln_empty(), iexamine::kiln_full(), Character::knock_back_to(), monster::knock_back_to(), Character::knows_trap(), iexamine::ledge(), explosion_handler::legacy_blast(), explosion_handler::legacy_shrapnel(), firestarter_actor::light_mod(), advanced_inventory_pane::load_settings(), iexamine::locked_object(), iexamine::locked_object_pickable(), activity_handlers::longsalvage_finish(), mattack::longswipe(), make_active(), make_mon_corpse(), trapfunc::map_regen(), map_selector::map_selector(), editmap::mapgen_preview(), editmap::mapgen_veh_destroy(), vehicle::merge_rackable_vehicle(), iexamine::migo_nerve_cluster(), activity_handlers::milk_finish(), monexamine::milk_source(), mill_activate(), iexamine::mill_finalize(), mill_load_food(), mine_activity(), iuse::modify_grid_connections(), Character::modify_morale(), monster::move(), npc::move(), avatar_action::move(), advanced_inventory::move_all_items(), npc::move_away_from(), move_cost(), explosion_handler::ExplosionProcess::move_entity(), move_item(), npc::move_to(), firestarter_actor::moves_cost_by_fuel(), Character::mutation_effect(), iexamine::nanofab(), nearest_passable(), iexamine::none(), iuse::note_bionics(), item::on_drop(), iexamine::on_smoke_out(), open(), vehicle::open_or_close(), iexamine::open_safe(), activity_handlers::operation_do_turn(), activity_handlers::operation_finish(), map_cursor::operator tripoint(), operator_present(), activity_handlers::oxytorch_finish(), vehicle::part_collision(), vehicle::part_removal_cleanup(), Character::passive_power_gen(), iexamine::pedestal_temple(), iexamine::pedestal_wyrm(), tutorial_game::per_turn(), Character::perform_install(), liquid_handler::perform_liquid_transfer(), Character::perform_uninstall(), perform_zone_activity_turn(), photo_def_for_camera_point(), pick_plant(), character_funcs::pick_safe_adjacent_tile(), npc::pick_up_item(), npc::pick_up_item_map(), activity_handlers::pickaxe_do_turn(), activity_handlers::pickaxe_finish(), iexamine::pit(), iexamine::pit_covered(), place_and_add_as_known(), place_construction(), Character::place_corpse(), basecamp::place_results(), iexamine::plant_seed(), activity_handlers::plant_seed_finish(), player_on_couch(), talk_function::player_weapon_drop(), pldrive(), points_for_gas_cloud(), iexamine::portable_structure(), tutorial_game::post_action(), iexamine::pour_into_keg(), firestarter_actor::prep_firestarter_use(), map_memory::prepare_region(), print_aim(), advanced_inventory::print_items(), item::process_cable(), item::process_extinguish(), item::process_fake_mill(), item::process_fake_smoke(), map::process_fields_in_submap(), item::process_internal(), item::process_litcig(), relic_funcs::process_recharge_entry(), item::process_rot(), sounds::process_sound_markers(), sounds::process_sounds(), explosion_handler::ExplosionProcess::project_shrapnel(), projectile_attack(), spell_effect::projectile_attack(), prompt_disassemble_single(), vehicle_part::properties_to_item(), activity_handlers::pry_nails_finish(), activity_handlers::pulp_do_turn(), monster::push_to(), put_into_vehicle(), put_into_vehicle_or_drop(), iexamine::quern_examine(), plot_options::query_seed(), mattack::ranged_pull(), character_funcs::rate_sleep_spot(), rcdrive(), Character::reach_attack(), npc::reach_omt_destination(), item::ready_to_revive(), target_ui::recalc_aim_turning_penalty(), editmap::recalc_target(), ranged::recoil_vehicle(), iexamine::recycle_compactor(), npc::regen_ai_cache(), iexamine::reload_furniture(), avatar_action::reload_weapon(), zone_manager::remove(), monexamine::remove_armor(), monexamine::remove_bag_from(), monexamine::remove_battery(), explosion_handler::ExplosionProcess::remove_field(), remove_submap_turrets(), map::remove_trap(), DefaultRemovePartHandler::removed(), veh_utils::repair_part(), iuse::report_grid_charge(), iuse::report_grid_connections(), requirements_map(), firestarter_actor::resolve_firestarter_use(), explosion_handler::explosion_funcs::resonance_cascade(), aim_activity_actor::restore_view(), zone_manager::revert_vzones(), mattack::riotbot(), rod_fish(), Character::rooted(), Character::rooted_message(), map::rotate(), route_adjacent(), iexamine::rubble(), explosion_handler::ExplosionProcess::run(), target_ui::run(), area_expander::run(), examine_item_menu::run(), Character::run_cost(), iexamine::safe(), mapbuffer::save(), npc::saw_player_recently(), scatter_chunks(), monster::scent_move(), character_funcs::search_surroundings(), npc::see_item_say_smth(), Creature::sees(), Character::sees(), npc::sees_dangerous_field(), Character::sees_with_infrared(), serialize_liquid_source(), advanced_inv_area::set_container_position(), target_ui::set_cursor_pos(), Character::set_destination(), DefaultRemovePartHandler::set_floor_cache_dirty(), conditional_t< T >::set_is_driving(), conditional_t< T >::set_is_outside(), set_item_map(), set_item_map_or_vehicle(), target_ui::set_last_target(), avatar::set_movement_mode(), npc::set_omt_destination(), DefaultRemovePartHandler::set_transparency_cache_dirty(), target_ui::set_view_offset(), editmap::setup_fmenu(), monexamine::shear_animal(), activity_handlers::shear_finish(), vehicle::shift_zlevel(), live_view::show(), mattack::shriek_stun(), iexamine::shrub_marloss(), iexamine::shrub_wildveggies(), Character::sight_range(), iexamine::sign(), sinkhole_safety_roll(), vehicle::slowdown(), smash(), map::smash_trap(), smoker_activate(), smoker_finalize(), smoker_load_food(), iexamine::smoker_options(), map::spawn_monsters_submap(), debug_menu::spawn_nested_mapgen(), spawn_spores(), spell_effect::spawn_summoned_vehicle(), spell_effect::spell_effect_blast(), spell_effect::spell_effect_cone(), spell_move(), item::spill_contents(), item_contents::spill_contents(), mdeath::splatter(), vehicle::split_vehicles(), Character::spores(), fungal_effects::spread_fungus(), map::spread_gas(), autodrive_activity_actor::start(), activity_handlers::start_engines_finish(), activity_handlers::start_fire_do_turn(), stash_on_pet(), vehicle::stop(), mattack::stretch_bite(), monster::stumble(), Character::suffer_from_asthma(), Character::suffer_from_other_mutations(), Character::suffer_from_radiation(), Character::suffer_in_sunlight(), Character::suffer_while_underwater(), Character::symbol_color(), ranged::targetable_creatures(), teleport::teleport(), tell_magic_veh_stop_following(), tell_magic_veh_to_follow(), tell_veh_stop_following(), terrain_collision_data(), test_passable(), vehicle::thrust(), tidy_activity(), gates::toggle_gate(), iexamine::toilet(), iexamine::toPumpFuel(), vehicle::total_wind_epower_w(), ter_furn_transform::transform(), iexamine::translocator(), iexamine::trap(), activity_handlers::travel_do_turn(), iexamine::tree_hickory(), iexamine::tree_maple(), iexamine::tree_maple_tapped(), iexamine::tree_marloss(), explosion_iuse::trigger_explosion(), try_fuel_fire(), target_ui::try_reacquire_target(), try_remove_bear_trap(), try_remove_grab(), try_remove_heavysnare(), try_remove_lightsnare(), avatar_funcs::try_to_sleep(), turnOnSelectedPump(), editmap::uber_draw_ter(), iuse::unfold_generic(), Character::uninstall_bionic(), unroll_digging(), distribution_grid_tracker::update(), update_lum(), Character::update_needs(), npc::update_path(), target_ui::update_status(), editmap::update_view_with_help(), weather_manager::update_weather(), iuse_transform::use(), unfold_vehicle_iuse::use(), consume_drug_iuse::use(), place_npc_iuse::use(), pick_lock_actor::use(), deploy_furn_actor::use(), firestarter_actor::use(), enzlave_actor::use(), place_trap_actor::use(), emit_actor::use(), deploy_tent_actor::use(), unpack_actor::use(), vehicle::use_bike_rack(), Character::use_fire(), iexamine::use_furn_fake_item(), basecamp::validate_sort_points(), vehicle_activity(), activity_handlers::vehicle_finish(), vehicle_selector::vehicle_selector(), iexamine::vending(), Character::vomit(), wait(), iexamine::water_source(), iuse::weather_tool(), avatar_action::wield(), workbench_crafting_speed_multiplier(), and npc::worker_downtime().
get_memory_at()
static int get_memory_at (const tripoint & p) static
Definition at line 5797 of file map.cpp.
{
    if( g->u.should_show_map_memory() ) {
        return g->u.get_memorized_symbol( g->m.getabs( p ) );
    }
    return ' ';
}
References g.
Referenced by map::draw().
get_sound_volume()
static int get_sound_volume (const map_bash_info & bash) static
Definition at line 3255 of file map.cpp.
{
    int smin = bash.str_min;
    int smax = bash.str_max;
    // TODO: Consider setting this in finalize instead of calculating here
    return bash.sound_vol.value_or( std::min( static_cast<int>( smin * 1.5 ), smax ) );
}
References spell_effect::bash().
Referenced by map::bash_furn_success(), and map::bash_ter_success().
has_memory_at()
static bool has_memory_at (const tripoint & p) static
Definition at line 5788 of file map.cpp.
{
    if( g->u.should_show_map_memory() ) {
        int t = g->u.get_memorized_symbol( g->m.getabs( p ) );
        return t != 0;
    }
    return false;
}
References g.
Referenced by map::draw().
process_map_items()
static bool process_map_items (item_stack & items, safe_reference< item > & item_ref, const tripoint & location, const temperature_flag flag) static
Definition at line 4558 of file map.cpp.
{
    if( item_ref->process( nullptr, location, false, flag ) ) {
        // Item is to be destroyed so erase it from the map stack
        // unless it was already destroyed by processing.
        if( item_ref ) {
            items.erase( items.get_iterator_from_pointer( item_ref.get() ) );
        }
        return true;
    }
    // Item not destroyed
    return false;
}
References item_stack::erase(), safe_reference< T >::get(), and item_stack::get_iterator_from_pointer().
Referenced by map::process_items_in_submap(), and map::process_items_in_vehicle().
process_vehicle_items()
static void process_vehicle_items (vehicle & cur_veh, int part) static
Definition at line 4573 of file map.cpp.
{
    const bool washmachine_here = cur_veh.part_flag( part, VPFLAG_WASHING_MACHINE ) &&
                                  cur_veh.is_part_on( part );
    bool washing_machine_finished = false;
    const bool dishwasher_here = cur_veh.part_flag( part, VPFLAG_DISHWASHER ) &&
                                 cur_veh.is_part_on( part );
    if( washmachine_here || dishwasher_here ) {
        for( auto &n : cur_veh.get_items( part ) ) {
            const time_duration washing_time = 90_minutes;
            const time_duration time_left = washing_time - n.age();
            static const std::string filthy( "FILTHY" );
            if( time_left <= 0_turns ) {
                n.unset_flag( filthy );
                washing_machine_finished = true;
                cur_veh.part( part ).enabled = false;
            } else if( calendar::once_every( 15_minutes ) ) {
                add_msg( _( "It should take %1$d minutes to finish washing items in the %2$s." ),
                         to_minutes<int>( time_left ) + 1, cur_veh.name );
                break;
            }
        }
        if( washing_machine_finished ) {
            if( washmachine_here ) {
                add_msg( _( "The washing machine in the %s has finished washing." ), cur_veh.name );
            } else if( dishwasher_here ) {
                add_msg( _( "The dishwasher in the %s has finished washing." ), cur_veh.name );
            }
        }
    }
    const int recharge_part_idx = cur_veh.part_with_feature( part, VPFLAG_RECHARGE, true );
    static const vehicle_part null_part;
    const vehicle_part &recharge_part = recharge_part_idx >= 0 ?
                                        cur_veh.part( recharge_part_idx ) :
                                        null_part;
    if( recharge_part_idx >= 0 && recharge_part.enabled &&
        !recharge_part.removed && !recharge_part.is_broken() ) {
        for( item &outer : cur_veh.get_items( part ) ) {
            bool out_of_battery = false;
            outer.visit_items( [&cur_veh, &recharge_part, &out_of_battery]( item * it ) {
                item &n = *it;
                if( !n.has_flag( flag_RECHARGE ) && !n.has_flag( flag_USE_UPS ) ) {
                    return VisitResponse::NEXT;
                }
                if( n.ammo_capacity() > n.ammo_remaining() ||
                    ( n.type->battery && n.type->battery->max_capacity > n.energy_remaining() ) ) {
                    int power = recharge_part.info().bonus;
                    while( power >= 1000 || x_in_y( power, 1000 ) ) {
                        const int missing = cur_veh.discharge_battery( 1, false );
                        if( missing > 0 ) {
                            out_of_battery = true;
                            return VisitResponse::ABORT;
                        }
                        if( n.is_battery() ) {
                            n.mod_energy( 1_kJ );
                        } else {
                            n.ammo_set( itype_battery, n.ammo_remaining() + 1 );
                        }
                        power -= 1000;
                    }
                    return VisitResponse::ABORT;
                }
                return VisitResponse::SKIP;
            } );
            if( out_of_battery ) {
                break;
            }
        }
    }
}
References _, ABORT, add_msg(), item::ammo_capacity(), item::ammo_remaining(), itype::battery, vehicle_part::enabled, item::energy_remaining(), flag_RECHARGE(), flag_USE_UPS(), vehicle::get_items(), item::has_flag(), vehicle_part::is_broken(), vehicle::is_part_on(), vehicle::name, calendar::once_every(), vehicle::part(), vehicle::part_flag(), vehicle::part_with_feature(), vehicle_part::removed, SKIP, item::type, VPFLAG_DISHWASHER, VPFLAG_RECHARGE, and VPFLAG_WASHING_MACHINE.
Referenced by map::process_items_in_vehicle().
sees_veh()
static bool sees_veh (const Creature & c, vehicle & veh, bool force_recalc) static
Definition at line 571 of file map.cpp.
{
    const auto &veh_points = veh.get_points( force_recalc );
    return std::any_of( veh_points.begin(), veh_points.end(), [&c]( const tripoint & pt ) {
        return c.sees( pt );
    } );
}
References c, and vehicle::get_points().
Referenced by map::move_vehicle().
shift_bitset_cache()
template<int SIZE, int MULTIPLIER> void shift_bitset_cache (std::bitset< SIZE *SIZE > & cache, point s)
Definition at line 6770 of file map.cpp.
{
    // sx shifts by MULTIPLIER rows, sy shifts by MULTIPLIER columns.
    int shift_amount = s.x * MULTIPLIER + s.y * SIZE * MULTIPLIER;
    if( shift_amount > 0 ) {
        cache >>= static_cast<size_t>( shift_amount );
    } else if( shift_amount < 0 ) {
        cache <<= static_cast<size_t>( -shift_amount );
    }
    // Shifting in the y direction shifted in 0 values, no no additional clearing is necessary, but
    // a shift in the x direction makes values "wrap" to the next row, and they need to be zeroed.
    if( s.x == 0 ) {
        return;
    }
    const size_t x_offset = s.x > 0 ? SIZE - MULTIPLIER : 0;
    for( size_t y = 0; y < SIZE; ++y ) {
        size_t y_offset = y * SIZE;
        for( size_t x = 0; x < MULTIPLIER; ++x ) {
            cache.reset( y_offset + x_offset + x );
        }
    }
}
References point::x, and point::y.
shift_bitset_cache< MAPSIZE, 1 >()
template void shift_bitset_cache< MAPSIZE, 1 > (std::bitset< MAPSIZE *MAPSIZE > & cache, point s)
Referenced by map::shift().
shift_bitset_cache< MAPSIZE_X, SEEX >()
template void shift_bitset_cache< MAPSIZE_X, SEEX > (std::bitset< MAPSIZE_X *MAPSIZE_X > & cache, point s)
Referenced by map::shift().
shift_tripoint_map()
template<typename T > static void shift_tripoint_map (std::map< tripoint, T > & map, point offset, const half_open_rectangle< point > & boundaries) inline static
Definition at line 6813 of file map.cpp.
{
    std::map<tripoint, T> old_map = std::move( map );
    map.clear();
    for( const std::pair<tripoint, T> &pr : old_map ) {
        tripoint new_pt = pr.first + offset;
        if( boundaries.contains( new_pt.xy() ) ) {
            map.emplace( new_pt, pr.second );
        }
    }
}
References half_open_rectangle< Point, >::contains(), avatar_action::move(), and tripoint::xy().
shift_tripoint_set()
static void shift_tripoint_set (std::set< tripoint > & set, point offset, const half_open_rectangle< point > & boundaries) inline static
Definition at line 6799 of file map.cpp.
{
    std::set<tripoint> old_set = std::move( set );
    set.clear();
    for( const tripoint &pt : old_set ) {
        tripoint new_pt = pt + offset;
        if( boundaries.contains( new_pt.xy() ) ) {
            set.insert( new_pt );
        }
    }
}
References half_open_rectangle< Point, >::contains(), avatar_action::move(), and tripoint::xy().
Referenced by map::shift().
temperature_flag_at_point()
static temperature_flag temperature_flag_at_point (const map & m, const tripoint & p) static
Definition at line 4700 of file map.cpp.
{
    if( m.ter( p ) == t_rootcellar ) {
        return temperature_flag::TEMP_ROOT_CELLAR;
    }
    if( m.has_flag_furn( TFLAG_FRIDGE, p ) ) {
        return temperature_flag::TEMP_FRIDGE;
    }
    if( m.has_flag_furn( TFLAG_FREEZER, p ) ) {
        return temperature_flag::TEMP_FREEZER;
    }
    return temperature_flag::TEMP_NORMAL;
}
References map::has_flag_furn(), t_rootcellar, TEMP_FREEZER, TEMP_FRIDGE, TEMP_NORMAL, TEMP_ROOT_CELLAR, map::ter(), TFLAG_FREEZER, and TFLAG_FRIDGE.
Referenced by map::actualize(), and map::process_items_in_submap().
use_amount_stack()
template<typename Stack > std::list< item > use_amount_stack (Stack stack, const itype_id & type, int & quantity, const std::function< bool(const item &)> & filter)
Definition at line 4876 of file map.cpp.
{
    std::list<item> ret;
    for( auto a = stack.begin(); a != stack.end() && quantity > 0; ) {
        if( a->use_amount( type, quantity, ret, filter ) ) {
            a = stack.erase( a );
        } else {
            ++a;
        }
    }
    return ret;
}
References a, cata::hash64_detail::ret, and type.
Referenced by map::use_amount_square().
use_charges_from_furn()
static void use_charges_from_furn (const furn_t & f, const itype_id & type, int & quantity, map * m, const tripoint & p, std::list< item > & ret, const std::function< bool(const item &)> & filter) static
Definition at line 4942 of file map.cpp.
{
    if( m->has_flag( "LIQUIDCONT", p ) ) {
        auto item_list = m->i_at( p );
        auto current_item = item_list.begin();
        for( ; current_item != item_list.end(); ++current_item ) {
            // looking for a liquid that matches
            if( filter( *current_item ) && current_item->made_of( LIQUID ) && type == current_item->typeId() ) {
                ret.push_back( *current_item );
                if( current_item->charges - quantity > 0 ) {
                    // Update the returned liquid amount to match the requested amount
                    ret.back().charges = quantity;
                    // Update the liquid item in the world to contain the leftover liquid
                    current_item->charges -= quantity;
                    // All the liquid needed was found, no other sources will be needed
                    quantity = 0;
                } else {
                    // The liquid copy in ret already contains how much was available
                    // The leftover quantity returned will check other sources
                    quantity -= current_item->charges;
                    // Remove liquid item from the world
                    item_list.erase( current_item );
                }
                return;
            }
        }
    }
    const std::vector<itype> item_list = f.crafting_pseudo_item_types();
    for( const itype &itt : item_list ) {
        if( itt.item_tags.count( flag_USES_GRID_POWER ) > 0 ) {
            const tripoint_abs_ms abspos( m->getabs( p ) );
            auto &grid = get_distribution_grid_tracker().grid_at( abspos );
            item furn_item( itt.get_id(), calendar::start_of_cataclysm, grid.get_resource() );
            int initial_quantity = quantity;
            if( filter( furn_item ) ) {
                furn_item.use_charges( type, quantity, ret, p );
                // That quantity math thing is atrocious. Punishment for the int& "argument".
                grid.mod_resource( quantity - initial_quantity );
            }
        } else if( itt.tool && !itt.tool->ammo_id.empty() ) {
            const itype_id ammo = ammotype( *itt.tool->ammo_id.begin() )->default_ammotype();
            auto stack = m->i_at( p );
            auto iter = std::find_if( stack.begin(), stack.end(),
            [ammo]( const item & i ) {
                return i.typeId() == ammo;
            } );
            if( iter != stack.end() ) {
                item furn_item( itt.get_id(), calendar::start_of_cataclysm, iter->charges );
                if( !filter( furn_item ) ) {
                    return;
                }
                // The item constructor limits the charges to the (type specific) maximum.
                // Setting it separately circumvents that it is synchronized with the code that creates
                // the pseudo item (and fills its charges) in inventory.cpp
                furn_item.charges = iter->charges;
                if( furn_item.use_charges( type, quantity, ret, p ) ) {
                    stack.erase( iter );
                } else {
                    iter->charges = furn_item.charges;
                }
            }
        }
    }
}
References item_stack::begin(), item::charges, furn_t::crafting_pseudo_item_types(), ammunition_type::default_ammotype(), flag_USES_GRID_POWER(), get_distribution_grid_tracker(), map::getabs(), distribution_grid_tracker::grid_at(), map::has_flag(), map::i_at(), LIQUID, cata::hash64_detail::ret, calendar::start_of_cataclysm, type, and item::use_charges().
Referenced by map::use_charges().
use_charges_from_stack()
template<typename Stack > std::list< item > use_charges_from_stack (Stack stack, const itype_id & type, int & quantity, const tripoint & pos, const std::function< bool(const item &)> & filter)
Definition at line 4928 of file map.cpp.
{
    std::list<item> ret;
    for( auto a = stack.begin(); a != stack.end() && quantity > 0; ) {
        if( !a->made_of( LIQUID ) && a->use_charges( type, quantity, ret, pos, filter ) ) {
            a = stack.erase( a );
        } else {
            ++a;
        }
    }
    return ret;
}
References a, LIQUID, wrapped_vehicle::pos, cata::hash64_detail::ret, and type.
Referenced by map::use_charges().
vehicle_caching_internal()
static void vehicle_caching_internal (level_cache & zch, const vpart_reference & vp, vehicle * v) static
Definition at line 8229 of file map.cpp.
{
    auto &outside_cache = zch.outside_cache;
    auto &transparency_cache = zch.transparency_cache;
    auto &floor_cache = zch.floor_cache;
    auto &obscured_cache = zch.vehicle_obscured_cache;
    auto &obstructed_cache = zch.vehicle_obstructed_cache;
    const size_t part = vp.part_index();
    const tripoint &part_pos =  v->global_part_pos3( vp.part() );
    bool vehicle_is_opaque = vp.has_feature( VPFLAG_OPAQUE ) && !vp.part().is_broken();
    if( vehicle_is_opaque ) {
        int dpart = v->part_with_feature( part, VPFLAG_OPENABLE, true );
        if( dpart < 0 || !v->part( dpart ).open ) {
            transparency_cache[part_pos.x][part_pos.y] = LIGHT_TRANSPARENCY_SOLID;
        } else {
            vehicle_is_opaque = false;
        }
    }
    if( vehicle_is_opaque || vp.is_inside() ) {
        outside_cache[part_pos.x][part_pos.y] = false;
    }
    if( vp.has_feature( VPFLAG_BOARDABLE ) && !vp.part().is_broken() ) {
        floor_cache[part_pos.x][part_pos.y] = true;
    }
    point t = v->tripoint_to_mount( part_pos + point_north_west );
    if( !v->allowed_light( t, vp.mount() ) ) {
        obscured_cache[part_pos.x][part_pos.y].nw = true;
    }
    if( !v->allowed_move( t, vp.mount() ) ) {
        obstructed_cache[part_pos.x][part_pos.y].nw = true;
    }
    t = v->tripoint_to_mount( part_pos + point_north_east );
    if( !v->allowed_light( t, vp.mount() ) ) {
        obscured_cache[part_pos.x][part_pos.y].ne = true;
    }
    if( !v->allowed_move( t, vp.mount() ) ) {
        obstructed_cache[part_pos.x][part_pos.y].ne = true;
    }
    if( part_pos.x > 0 && part_pos.y < MAPSIZE_Y - 1 ) {
        t = v->tripoint_to_mount( part_pos + point_south_west );
        if( !v->allowed_light( t, vp.mount() ) ) {
            obscured_cache[part_pos.x - 1][part_pos.y + 1].ne = true;
        }
        if( !v->allowed_move( t, vp.mount() ) ) {
            obstructed_cache[part_pos.x - 1][part_pos.y + 1].ne = true;
        }
    }
    if( part_pos.x < MAPSIZE_X - 1 && part_pos.y < MAPSIZE_Y - 1 ) {
        t = v->tripoint_to_mount( part_pos + point_south_east );
        if( !v->allowed_light( t, vp.mount() ) ) {
            obscured_cache[part_pos.x + 1][part_pos.y + 1].nw = true;
        }
        if( !v->allowed_move( t, vp.mount() ) ) {
            obstructed_cache[part_pos.x + 1][part_pos.y + 1].nw = true;
        }
    }
}
References vehicle::allowed_light(), vehicle::allowed_move(), level_cache::floor_cache, vehicle::global_part_pos3(), vpart_reference::has_feature(), vehicle_part::is_broken(), vpart_position::is_inside(), LIGHT_TRANSPARENCY_SOLID, MAPSIZE_X, MAPSIZE_Y, vpart_position::mount(), open(), level_cache::outside_cache, vpart_reference::part(), vpart_position::part_index(), vehicle::part_with_feature(), point_north_east, point_north_west, point_south_east, point_south_west, level_cache::transparency_cache, vehicle::tripoint_to_mount(), level_cache::vehicle_obscured_cache, level_cache::vehicle_obstructed_cache, VPFLAG_BOARDABLE, VPFLAG_OPAQUE, VPFLAG_OPENABLE, tripoint::x, and tripoint::y.
Referenced by map::do_vehicle_caching().
vehicle_caching_internal_above()
static void vehicle_caching_internal_above (level_cache & zch_above, const vpart_reference & vp, vehicle * v) static
Definition at line 8296 of file map.cpp.
{
    if( vp.has_feature( VPFLAG_ROOF ) || vp.has_feature( VPFLAG_OPAQUE ) ) {
        const tripoint &part_pos = v->global_part_pos3( vp.part() );
        zch_above.floor_cache[part_pos.x][part_pos.y] = true;
    }
}
References level_cache::floor_cache, vehicle::global_part_pos3(), vpart_reference::has_feature(), vpart_reference::part(), VPFLAG_OPAQUE, VPFLAG_ROOF, tripoint::x, and tripoint::y.
Referenced by map::do_vehicle_caching().
will_explode_on_impact()
static bool will_explode_on_impact (const int power) static
Definition at line 3039 of file map.cpp.
{
    const auto explode_threshold = get_option<int>( "MADE_OF_EXPLODIUM" );
    const bool is_explodium = explode_threshold != 0;
    return is_explodium && power >= explode_threshold;
}
Referenced by map::smash_items(), and map::smash_trap().
Variable Documentation
ammo_effect_INCENDIARY
const ammo_effect_str_id ammo_effect_INCENDIARY("INCENDIARY") ("INCENDIARY") static
Referenced by map::shoot().
ammo_effect_LASER
const ammo_effect_str_id ammo_effect_LASER("LASER") ("LASER") static
Referenced by map::shoot().
ammo_effect_LIGHTNING
const ammo_effect_str_id ammo_effect_LIGHTNING("LIGHTNING") ("LIGHTNING") static
Referenced by map::shoot().
ammo_effect_PLASMA
const ammo_effect_str_id ammo_effect_PLASMA("PLASMA") ("PLASMA") static
Referenced by map::shoot().
disable_mapgen
bool disable_mapgen = false
Causes all generated maps to be empty grass and prevents saved maps from being loaded, used by the test suite.
Definition at line 145 of file map.cpp.
Referenced by mapgen_factory::generate(), and mapbuffer::save_quad().
effect_boomered
const efftype_id effect_boomered("boomered") ("boomered") static
Referenced by map::update_visibility_cache().
effect_crushed
const efftype_id effect_crushed("crushed") ("crushed") static
Referenced by map::crush(), and map::furn_set().
itype_autoclave
const itype_id itype_autoclave("autoclave") ("autoclave") static
Referenced by map::use_charges().
itype_battery
const itype_id itype_battery("battery") ("battery") static
Referenced by map::use_charges().
itype_chemistry_set
const itype_id itype_chemistry_set("chemistry_set") ("chemistry_set") static
Referenced by map::use_charges().
itype_dehydrator
const itype_id itype_dehydrator("dehydrator") ("dehydrator") static
Referenced by map::use_charges().
itype_electrolysis_kit
const itype_id itype_electrolysis_kit("electrolysis_kit") ("electrolysis_kit") static
Referenced by map::use_charges().
itype_food_processor
const itype_id itype_food_processor("food_processor") ("food_processor") static
Referenced by map::use_charges().
itype_forge
const itype_id itype_forge("forge") ("forge") static
Referenced by map::use_charges().
itype_hotplate
const itype_id itype_hotplate("hotplate") ("hotplate") static
Referenced by map::use_charges().
itype_kiln
const itype_id itype_kiln("kiln") ("kiln") static
Referenced by map::use_charges().
itype_nail
const itype_id itype_nail("nail") ("nail") static
itype_press
const itype_id itype_press("press") ("press") static
Referenced by map::use_charges().
itype_soldering_iron
const itype_id itype_soldering_iron("soldering_iron") ("soldering_iron") static
Referenced by map::use_charges().
itype_vac_sealer
const itype_id itype_vac_sealer("vac_sealer") ("vac_sealer") static
Referenced by map::use_charges().
itype_welder
const itype_id itype_welder("welder") ("welder") static
Referenced by map::use_charges().
mon_zombie
const mtype_id mon_zombie("mon_zombie") ("mon_zombie") static
Referenced by map::add_corpse().
nulfield
field nulfield static
Definition at line 142 of file map.cpp.
Referenced by map::field_at().
nulitems
cata::colony<item> nulitems static
Definition at line 141 of file map.cpp.
Referenced by map::i_at().
null_submap
submap null_submap static
Definition at line 258 of file map.cpp.
Referenced by map::maptile_at().
nullcache
level_cache nullcache static
Definition at line 143 of file map.cpp.
Referenced by map::access_cache().
skill_traps
const skill_id skill_traps("traps") ("traps") static
Referenced by map::disarm_trap().
t_rock_floor_no_roof
const ter_str_id t_rock_floor_no_roof("t_rock_floor_no_roof") ("t_rock_floor_no_roof") static
Referenced by map::get_roof().