Cataclysm BN: anonymous_namespace{item.cpp} Namespace Reference
anonymous_namespace{item.cpp} Namespace Reference
Functions
auto temperature_flag_to_highest_temperature (temperature_flag temperature) -> units::temperature
const std::string & get_clothing_mod_val_key (clothing_mod_type type)
Variables
constexpr auto rot_chart
Hardcoded lookup table for food rots per hour calculation.
Function Documentation
get_clothing_mod_val_key()
const std::string & anonymous_namespace{item.cpp}::get_clothing_mod_val_key (clothing_mod_type type)
Definition at line 10152 of file item.cpp.
{
    const static auto cache = ( []() {
        std::array<std::string, clothing_mods::all_clothing_mod_types.size()> res;
        for( const clothing_mod_type &type : clothing_mods::all_clothing_mod_types ) {
            res[type] = CLOTHING_MOD_VAR_PREFIX
                        + clothing_mods::string_from_clothing_mod_type( clothing_mods::all_clothing_mod_types[type] );
        }
        return res;
    } )();
    return cache[ type ];
}
References clothing_mods::all_clothing_mod_types, CLOTHING_MOD_VAR_PREFIX(), clothing_mods::string_from_clothing_mod_type(), and type.
Referenced by item::get_clothing_mod_val(), and item::update_clothing_mod_val().
temperature_flag_to_highest_temperature()
auto anonymous_namespace{item.cpp}::temperature_flag_to_highest_temperature (temperature_flag temperature) -> units::temperature
Definition at line 5690 of file item.cpp.
{
    switch( temperature ) {
        case temperature_flag::TEMP_NORMAL:
        case temperature_flag::TEMP_HEATER:
            return units::temperature_max;
        case temperature_flag::TEMP_FRIDGE:
            return temperatures::fridge;
        case temperature_flag::TEMP_FREEZER:
            return temperatures::freezer;
        case temperature_flag::TEMP_ROOT_CELLAR:
            return temperatures::root_cellar;
    }
    return units::temperature_max;
}
References temperatures::freezer, temperatures::fridge, temperatures::root_cellar, TEMP_FREEZER, TEMP_FRIDGE, TEMP_HEATER, TEMP_NORMAL, TEMP_ROOT_CELLAR, and units::temperature_max.
Referenced by item::minimum_freshness_duration().
Variable Documentation
rot_chart
constexpr auto anonymous_namespace{item.cpp}::rot_chart constexpr
Initial value:
= std::array<int, 44>
{
    0, 372, 744, 1118, 1219, 1273, 1388, 1514, 1651, 1800,
    1880, 2050, 2235, 2438, 2658, 2776, 3027, 3301, 3600, 3926,
    4100, 4471, 4875, 5317, 5798, 6054, 6602, 7200, 7852, 8562,
    8941, 9751, 10633, 11595, 12645, 13205, 14400, 15703, 17125, 18674,
    19501,
}
Hardcoded lookup table for food rots per hour calculation.
IRL this tends to double every 10c a few degrees above freezing, but past a certain point the rate decreases until even extremophiles find it too hot. Here we just stop further acceleration at 40C.
Original formula:
See also
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/033901af4b52ad0bfcfd6abfe06bca4e403d44b1/src/item.cpp#L5612-L5640
Definition at line 5627 of file item.cpp.
Referenced by get_hourly_rotpoints_at_temp().