Cataclysm BN: npc_ai Namespace Reference
npc_ai Namespace Reference
Functions
double wielded_value (const Character &who, bool ideal)
Evaluate wielded weapon.
double weapon_value (const Character &who, const item &weap, int ammo)
Evaluate item as weapon (melee or gun)
double gun_value (const Character &who, const item &weap, int ammo)
Evaluates item as a gun.
double melee_value (const Character &who, const item &weap)
Evaluate item as a melee weapon.
double unarmed_value (const Character &who)
Evaluate unarmed melee value.
Function Documentation
gun_value()
double npc_ai::gun_value (const Character & who, const item & weap, int ammo)
Evaluates item as a gun.
Definition at line 1970 of file ranged.cpp.
{
    // TODO: Mods
    // TODO: Allow using a specified type of ammo rather than default or current
    if( !weap.type->gun ) {
        return 0.0;
    }
    if( ammo <= 0 ) {
        return 0.0;
    }
    itype_id ammo_type;
    if( !weap.ammo_current().is_null() ) {
        ammo_type = weap.ammo_current();
    } else if( weap.magazine_current() ) {
        ammo_type = weap.common_ammo_default();
    } else {
        ammo_type = weap.ammo_default();
    }
    const itype *def_ammo_i = ammo_type.is_null() ? nullptr : &*ammo_type;
    damage_instance gun_damage = weap.gun_damage();
    const int ammo_cap = weap.ammo_capacity();
    bool empty = weap.ammo_remaining() == 0;
    item tmp = weap;
    tmp.ammo_set( ammo_type );
    int total_dispersion = ranged::get_weapon_dispersion( who, tmp ).max() +
                           ranged::effective_dispersion( who, tmp.sight_dispersion() );
    if( def_ammo_i != nullptr && def_ammo_i->ammo ) {
        const islot_ammo &def_ammo = *def_ammo_i->ammo;
        gun_damage.add( def_ammo.damage );
        total_dispersion += def_ammo.dispersion;
    }
    float damage_factor = gun_damage.total_damage();
    if( damage_factor > 0 ) {
        // TODO: Multiple damage types
        damage_factor += 0.5f * gun_damage.damage_units.front().res_pen;
    }
    int move_cost = time_to_attack( who, weap, item_location() );
    if( empty && ammo >= 1 ) {
        int reload_cost = weap.get_reload_time() + who.encumb( bp_hand_l ) + who.encumb( bp_hand_r );
        move_cost += reload_cost;
    }
    // Gives an approximation of DPS disregarding modes.
    float move_cost_factor = move_cost / 100.0f;
    // "Medium range" below means 9 tiles, "short range" means 4
    // Those are guarantees (assuming maximum time spent aiming)
    static const std::vector<std::pair<float, float>> dispersion_thresholds = {
        {
            // Headshots all the time
            { 0.0f, 5.0f },
            // Critical at medium range
            { 100.0f, 4.5f },
            // Critical at short range or good hit at medium
            { 200.0f, 3.5f },
            // OK hits at medium
            { 300.0f, 3.0f },
            // Point blank headshots
            { 450.0f, 2.5f },
            // OK hits at short
            { 700.0f, 1.5f },
            // Glances at medium, criticals at point blank
            { 1000.0f, 1.0f },
            // Nothing guaranteed, pure gamble
            { 2000.0f, 0.1f },
        }
    };
    float dispersion_factor = multi_lerp( dispersion_thresholds, total_dispersion );
    float damage_and_accuracy = damage_factor * dispersion_factor;
    // TODO: Some better approximation of the ability to keep on shooting
    static const std::vector<std::pair<float, float>> capacity_thresholds = {
        {
            { 1.0f, 0.5f },
            { 5.0f, 1.0f },
            { 10.0f, 1.5f },
            { 20.0f, 2.0f },
            { 50.0f, 3.0f },
        }
    };
    // Ammo capacity. Reduced to ammo available if that's lower.
    float capacity = ammo_cap > 0 ? std::min( ammo_cap, ammo ) : ammo;
    double capacity_factor = multi_lerp( capacity_thresholds, capacity );
    double gun_value = damage_and_accuracy * capacity_factor * move_cost_factor;
    add_msg( m_debug, "%s as gun: %.1f total, %.1f dispersion, %.1f damage, %.1f capacity, %.1f move",
             weap.type->get_id().str(), gun_value, dispersion_factor, damage_factor,
             capacity_factor, move_cost_factor );
    return std::max( 0.0, gun_value );
}
References damage_instance::add(), add_msg(), itype::ammo, item::ammo_capacity(), item::ammo_current(), item::ammo_default(), item::ammo_remaining(), item::ammo_set(), bp_hand_l, bp_hand_r, item::common_ammo_default(), common_ranged_data::damage, damage_instance::damage_units, common_ranged_data::dispersion, ranged::effective_dispersion(), Character::encumb(), itype::get_id(), item::get_reload_time(), ranged::get_weapon_dispersion(), itype::gun, item::gun_damage(), gun_value(), string_id< T >::is_null(), m_debug, item::magazine_current(), dispersion_sources::max(), move_cost(), multi_lerp(), item::sight_dispersion(), string_id< T >::str(), time_to_attack(), damage_instance::total_damage(), and item::type.
Referenced by gun_value(), and weapon_value().
melee_value()
double npc_ai::melee_value (const Character & who, const item & weap)
Evaluate item as a melee weapon.
Definition at line 2337 of file melee.cpp.
{
    // start with average effective dps against a range of enemies
    double my_value = weap.average_dps( *who.as_player() );
    float reach = weap.reach_range( who );
    // value reach weapons more
    if( reach > 1.0f ) {
        my_value *= 1.0f + 0.5f * ( std::sqrt( reach ) - 1.0f );
    }
    // value polearms less to account for the trickiness of keeping the right range
    if( weap.has_flag( "POLEARM" ) ) {
        my_value *= 0.8;
    }
    // value style weapons more
    if( !who.martial_arts_data->enumerate_known_styles( weap.type->get_id() ).empty() ) {
        my_value *= 1.5;
    }
    add_msg( m_debug, "%s as melee: %.1f", weap.type->get_id().str(), my_value );
    return std::max( 0.0, my_value );
}
References add_msg(), Creature::as_player(), item::average_dps(), itype::get_id(), item::has_flag(), m_debug, Character::martial_arts_data, item::reach_range(), string_id< T >::str(), and item::type.
Referenced by npc::average_damage_dealt(), unarmed_value(), and weapon_value().
unarmed_value()
double npc_ai::unarmed_value (const Character & who)
Evaluate unarmed melee value.
Definition at line 2362 of file melee.cpp.
{
    // TODO: Martial arts
    return melee_value( who, item() );
}
References melee_value().
weapon_value()
double npc_ai::weapon_value (const Character & who, const item & weap, int ammo)
Evaluate item as weapon (melee or gun)
Definition at line 2318 of file melee.cpp.
{
    const double val_gun = gun_value( who, weap, ammo );
    const double val_melee = melee_value( who, weap );
    const double more = std::max( val_gun, val_melee );
    const double less = std::min( val_gun, val_melee );
    // discourage wielding helmets, but not worn firearms
    int armor_penalty = 1;
    if( weap.is_armor() && !weap.is_gun() ) {
        armor_penalty = 0;
    }
    // A small bonus for guns you can also use to hit stuff with (bayonets etc.)
    const double my_val = ( more + ( less / 2.0 ) ) * armor_penalty;
    add_msg( m_debug, "%s (%ld ammo) sum value: %.1f", weap.type->get_id().str(), ammo, my_val );
    return my_val;
}
References add_msg(), itype::get_id(), gun_value(), item::is_armor(), item::is_gun(), m_debug, melee_value(), detail::digits::more, string_id< T >::str(), and item::type.
Referenced by npc::check_or_use_weapon_cbm(), give_item_to(), npc::value(), and npc::wield_better_weapon().
wielded_value()
double npc_ai::wielded_value (const Character & who, bool ideal)
Evaluate wielded weapon.
Definition at line 2291 of file melee.cpp.
{
    const double cached = ideal ? *who.get_npc_ai_info_cache( npc_ai_info::ideal_weapon_value ) :
                          *who.get_npc_ai_info_cache( npc_ai_info::weapon_value );
    if( cached >= 0.0 ) {
        if( ideal ) {
            add_msg( m_debug, "%s ideal sum value: %.1f", who.primary_weapon().type->get_id().str(), cached );
        } else {
            add_msg( m_debug, "%s cached sum value: %.1f", who.primary_weapon().type->get_id().str(), cached );
        }
        return cached;
    }
    int ammo_count = ideal ? who.primary_weapon().ammo_capacity() :
                     character_funcs::ammo_count_for( who, who.primary_weapon() );
    item ideal_weapon = who.primary_weapon();
    if( !ideal_weapon.ammo_default().is_null() ) {
        ideal_weapon.ammo_set( ideal_weapon.ammo_default(), -1 );
    }
    double weap_val = weapon_value( who, ideal ? ideal_weapon : who.primary_weapon(), ammo_count );
    if( ideal ) {
        who.set_npc_ai_info_cache( npc_ai_info::ideal_weapon_value, weap_val );
    } else {
        who.set_npc_ai_info_cache( npc_ai_info::weapon_value, weap_val );
    }
    return weap_val;
}
References add_msg(), item::ammo_capacity(), character_funcs::ammo_count_for(), item::ammo_default(), item::ammo_set(), itype::get_id(), Character::get_npc_ai_info_cache(), ideal_weapon_value, string_id< T >::is_null(), m_debug, Character::primary_weapon(), Character::set_npc_ai_info_cache(), string_id< T >::str(), item::type, and weapon_value.
Referenced by npc::character_danger(), npc::check_or_use_weapon_cbm(), npc::decide_needs(), npc::form_opinion(), rate_critter(), npc::regen_ai_cache(), npc::value(), and npc::wield_better_weapon().