Cataclysm BN: anonymous_namespace{iexamine_elevator.cpp}::elevator Namespace Reference
anonymous_namespace{iexamine_elevator.cpp}::elevator Namespace Reference
Classes
struct elevator_vehicles
Typedefs
using tiles = std::vector< tripoint >
Enumerations
enum class overlap_status { outside , inside , overlap }
Functions
auto here (const Character &you) -> elevator::tiles
auto dest (const elevator::tiles &elevator_here, const tripoint &sm_orig, int turns, int movez) -> elevator::tiles
auto choose_floor (const tripoint &examp, const tripoint_abs_omt &this_omt, const tripoint &sm_orig) -> int
auto vehicle_status (const wrapped_vehicle &veh, const elevator::tiles &tiles) -> overlap_status
auto vehicles_on (const elevator::tiles &tiles) -> elevator_vehicles
auto warn_blocking (const elevator_vehicles &vehs, std::string_view location) -> void
auto move_creatures_away (const elevator::tiles &dest) -> void
auto move_items (const elevator::tiles from, const elevator::tiles dest) -> void
auto move_creatures (const elevator::tiles from, const elevator::tiles dest) -> void
auto move_vehicles (const elevator_vehicles &vehs, const tripoint &sm_orig, int movez, int turns) -> void
Typedef Documentation
tiles
using anonymous_namespace{iexamine_elevator.cpp}::elevator::tiles = typedef std::vector<tripoint>
Definition at line 33 of file iexamine_elevator.cpp.
Enumeration Type Documentation
overlap_status
enum class anonymous_namespace{iexamine_elevator.cpp}::elevator::overlap_status strong
Enumerator
outside
inside
overlap
Definition at line 91 of file iexamine_elevator.cpp.
{ outside, inside, overlap };
Function Documentation
choose_floor()
auto anonymous_namespace{iexamine_elevator.cpp}::elevator::choose_floor (const tripoint & examp, const tripoint_abs_omt & this_omt, const tripoint & sm_orig) -> int
Definition at line 63 of file iexamine_elevator.cpp.
{
    constexpr int retval_offset = 10000; // workaround for uilist retval autoassign when retval == -1
    const auto this_floor = _( " (this floor)" );
    map &here = get_map();
    uilist choice;
    choice.title = _( "Please select destination floor" );
    for( int z = OVERMAP_HEIGHT; z >= -OVERMAP_DEPTH; z-- ) {
        const tripoint_abs_omt that_omt{ this_omt.xy(), z };
        const int turns = get_rot_turns( this_omt, that_omt );
        const tripoint zp =
            rotate_point_sm( { examp.xy(), z }, sm_orig, turns );
        if( here.ter( zp )->examine != &iexamine::elevator ) {
            continue;
        }
        const std::string omt_name = overmap_buffer.ter_existing( that_omt )->get_name();
        const auto floor_name = z == examp.z ? this_floor : "";
        const std::string name = string_format( "%3iF %s%s", z, omt_name, floor_name );
        choice.addentry( z + retval_offset, z != examp.z, MENU_AUTOASSIGN, name );
    }
    choice.query();
    return choice.ret - retval_offset;
}
References _, uilist::addentry(), iexamine::elevator(), get_map(), oter_t::get_name(), get_rot_turns(), here(), MENU_AUTOASSIGN, om_direction::name(), overmap_buffer, OVERMAP_DEPTH, OVERMAP_HEIGHT, uilist::query(), uilist::ret, rotate_point_sm(), string_format(), overmapbuffer::ter_existing(), uilist::title, and coords::coord_point< Point, Origin, Scale >::xy().
Referenced by iexamine::elevator().
dest()
auto anonymous_namespace{iexamine_elevator.cpp}::elevator::dest (const elevator::tiles & elevator_here, const tripoint & sm_orig, int turns, int movez) -> elevator::tiles
Definition at line 49 of file iexamine_elevator.cpp.
{
    elevator::tiles tiles;
    std::transform( elevator_here.begin(), elevator_here.end(), std::back_inserter( tiles ),
    [turns, &sm_orig, movez]( tripoint const & p ) {
        return rotate_point_sm( { p.xy(), movez }, sm_orig, turns );
    } );
    return tiles;
}
References iexamine::transform().
Referenced by mattack::acid(), computer_session::action_blood_anal(), computer_session::action_cascade(), computer_session::action_conveyor(), computer_session::action_data_anal(), computer_session::action_deactivate_shock_vent(), computer_session::action_extract_rad_source(), computer_session::action_geiger(), computer_session::action_irradiator(), activity_on_turn_move_loot(), mattack::antqueen(), apply_region_overlay(), iuse::artifact(), detail::bit_cast(), mdeath::boomer(), mdeath::boomer_glow(), mattack::breathe(), overmap::build_connection(), leap_actor::call(), iuse::call_of_tindalos(), talk_function::caravan_depart(), talk_function::caravan_dist(), talk_function::caravan_return(), deploy_tent_actor::check_intact(), mdeath::conflagration(), debug_menu::debug(), move_items_activity_actor::do_turn(), inventory::dump(), iexamine::elevator(), iuse::extinguisher(), npc::faction_display(), computer_session::failure_destroy_blood(), npc::find_item(), game::find_or_make_stairs(), pf::find_overmap_path(), mattack::formblob(), iuse::fungicide(), mattack::fungus_big_blossom(), mattack::fungus_fortify(), mattack::fungus_haze(), mattack::fungus_sprout(), Character::get_dodge(), get_heat_radiation(), overmap_ui::get_overmap_neighbors(), overmap_ui::get_overmap_path_to(), overmapbuffer::get_travel_path(), iuse::granade_act(), pf::greedy_path(), iuse::grenade_inc_act(), Character::hardcoded_effects(), overmap::lay_out_connection(), trapfunc::ledge(), iexamine::ledge(), explosion_handler::legacy_blast(), load_region_settings(), game::monmove(), monster::move(), move_cost(), move_cost_cart(), move_cost_inv(), move_creatures(), move_creatures_away(), inventory_column::move_entries_to(), anonymous_namespace{iexamine_elevator.cpp}::move_item(), move_item(), move_items(), om_line_mark(), om_target_tile(), trap::on_disarmed(), Character::perform_technique(), game::phasing_move(), iuse::pheromone(), npc::pick_up_item(), monster::plan(), tutorial_game::post_action(), game::process_artifact(), relic_funcs::process_recharge_entry(), monster::process_turn(), projectile_attack(), activity_handlers::pulp_do_turn(), monster::push_to(), rcdrive(), vehicle::remove_part(), explosion_handler::explosion_funcs::resonance_cascade(), mission_util::reveal_road(), overmapbuffer::reveal_route(), mattack::riotbot(), map::route(), route_adjacent(), monster::scent_move(), mattack::searchlight(), mattack::shockstorm(), vehicle::slow_leak(), spawn_spores(), vehicle::spew_field(), fungal_effects::spread_fungus(), monster::stumble(), iuse::throwable_extinguisher_act(), mattack::tindalos_teleport(), mattack::triffid_heartbeat(), explosion_iuse::trigger_explosion(), try_remove_grab(), game::update_stair_monsters(), deploy_tent_actor::use(), mattack::vine(), and mdeath::vine_cut().
here()
auto anonymous_namespace{iexamine_elevator.cpp}::elevator::here (const Character & you) -> elevator::tiles
Definition at line 35 of file iexamine_elevator.cpp.
{
    const auto &here = get_map();
    const auto &points = closest_points_first( you.pos(), SEEX - 1 );
    elevator::tiles tiles;
    std::copy_if( points.begin(), points.end(), std::back_inserter( tiles ),
    [&here]( const tripoint & pos ) {
        return here.has_flag( TFLAG_ELEVATOR, pos );
    } );
    return tiles;
}
References closest_points_first(), get_map(), here(), and SEEX.
Referenced by basecamp::abandon_camp(), Character::absorb_hit(), vehicle::act_on_map(), computer_session::action_blood_anal(), computer_session::action_cascade(), computer_session::action_conveyor(), computer_session::action_data_anal(), computer_session::action_deactivate_shock_vent(), computer_session::action_elevator_on(), computer_session::action_extract_rad_source(), computer_session::action_geiger(), computer_session::action_irradiator(), computer_session::action_list_bionics(), computer_session::action_portal(), computer_session::action_sample(), computer_session::action_srcf_elevator(), computer_session::action_srcf_seal(), computer_session::action_terminate(), Character::activate_bionic(), activity_on_turn_move_loot(), zone_manager::add(), add_basecamp_storage_to_loot_zone_list(), explosion_handler::ExplosionProcess::add_field(), vehicle::add_item(), vehicle::advance_precalc_mounts(), iexamine::aggie_plant(), npc::alt_attack(), item_stack::amount_can_fit(), apply< furn_t >(), apply< ter_t >(), apply< trap >(), apply_ammo_effects(), apply_camp_ownership(), apply_lock_picking_tool(), apply_prying_tool(), iexamine::arcfurnace_empty(), iexamine::arcfurnace_full(), are_requirements_nearby(), npc::assess_danger(), Creature::auto_find_hostile_target(), iexamine::autoclave_full(), iexamine::bars(), character_funcs::base_comfort_value(), talk_function::basecamp_mission(), explosion_handler::ExplosionProcess::blast_tile(), Character::blossoms(), mattack::boomer(), mattack::boomer_glow(), activity_handlers::build_do_turn(), iexamine::bulletin_board(), Character::burn_fuel(), activity_handlers::burrow_finish(), butcher_corpse_activity(), activity_handlers::butcher_finish(), butchery_drops_harvest(), butchery_quarter(), leap_actor::call(), can_construct(), can_do_activity_there(), can_examine_at(), iexamine::can_fertilize(), can_interact_at(), npc::can_move_to(), can_move_vertical_at(), can_pickup_at(), monster::can_reach_to(), iexamine::cardreader(), iexamine::cardreader_foodplace(), iexamine::chainfence(), game::chat(), check_art_charge_req(), construct::check_deconstruct(), vehicle::autodrive_controller::check_drivable(), player::check_eligible_containers_for_crafting(), construct::check_empty(), vehicle::check_falling_or_floating(), vehicle::check_heli_ascend(), vehicle::check_heli_descend(), deploy_tent_actor::check_intact(), Character::check_outbounds_activity(), construct::check_support(), choose_adjacent_highlight(), choose_floor(), target_ui::choose_initial_target(), activity_handlers::chop_logs_finish(), chop_plank_activity(), activity_handlers::chop_planks_finish(), chop_tree_activity(), activity_handlers::chop_tree_do_turn(), activity_handlers::chop_tree_finish(), activity_handlers::churn_finish(), cleanup_tiles(), activity_handlers::clear_rubble_finish(), talk_function::companion_return(), complete_construction(), veh_interact::complete_vehicle(), vehicle::autodrive_controller::compute_obstacles(), consider_butchery(), construction_activity(), Character::consume_remote_fuel(), npc::could_move_onto(), spell::create_field(), iexamine::curtains(), salvage_actor::cut_up(), cycle_action(), vehicle::damage_direct(), monexamine::deactivate_pet(), iexamine::deployed_furniture(), iexamine::dirtmound(), displace_items_except_one_liquid(), veh_interact::display_veh(), basecamp::distribute_food(), character_funcs::do_pause(), construct::done_deconstruct(), construct::done_digormine_stair(), construct::done_extract_maybe_revert_to_dirt(), construct::done_grave(), construct::done_mine_upstair(), construct::done_window_curtains(), iexamine::door_peephole(), editmap_hilight::draw(), explosion_handler::draw_custom_explosion(), anonymous_namespace{animation.cpp}::draw_line_curses(), editmap::draw_main_ui_overlay(), npc::drop_items(), drop_on_map(), drop_or_embed_projectile(), talk_function::drop_stolen_item(), monexamine::dump_items(), avatar_action::eat_here(), editmap::edit_fld(), editmap::edit_mapgen(), iexamine::egg_sack_generic(), iexamine::elevator(), explosion_handler::emp_blast(), enumerate_objects_around_point(), Character::env_surgery_bonus(), npc::execute_action(), ranged::execute_shaped_attack(), ranged::expected_coverage(), computer_session::failure_destroy_blood(), computer_session::failure_destroy_data(), computer_session::failure_pump_explode(), computer_session::failure_pump_leak(), computer_session::failure_shutdown(), farm_action(), iexamine::fertilize_plant(), fetch_activity(), activity_handlers::fill_liquid_do_turn(), explosion_handler::ExplosionProcess::fill_maps(), activity_handlers::fill_pit_finish(), find_auto_consume(), find_base_construction(), find_best_fire(), find_closest_stair(), npc::find_corpse_to_pulp(), find_empty_spot_nearby(), npc::find_item(), find_refuel_spot_zone(), Character::find_remote_fuel(), anonymous_namespace{mattack_actors.cpp}::find_target_vehicle(), dig_activity_actor::finish(), dig_channel_activity_actor::finish(), hacking_activity_actor::finish(), fire(), ranged::fire_gun(), iexamine::fireplace(), mattack::flame(), explosion_handler::explosion_funcs::flashbang(), Character::floor_bedding_warmth(), Character::floor_item_warmth(), iexamine::flower_cactus(), iexamine::flower_dahlia(), iexamine::flower_marloss(), iexamine::flower_poppy(), activity_handlers::forage_finish(), fromPumpFuel(), iexamine::fswitch(), iexamine::fungus(), iexamine::fvat_empty(), iexamine::fvat_full(), iexamine::gaspump(), generic_multi_activity_check_requirement(), generic_multi_activity_do(), generic_multi_activity_handler(), generic_multi_activity_locations(), item::get_cable_target(), advanced_inv_area::get_container(), get_convection_temperature(), player::get_eligible_containers_for_crafting(), get_fire_fuel_string(), get_hack_type(), get_heat_radiation(), liquid_handler::get_liquid_target(), overmap_ui::get_overmap_path_to(), zone_manager::get_point_set_loot(), get_rot_turns(), iexamine::getGasPumpByNumber(), iexamine::getNearFilledGasTank(), getNearPumpCount(), npc::go_to_omt_destination(), npc::good_escape_direction(), good_fishing_spot(), grab(), activity_handlers::hacksaw_finish(), handbrake(), handle_action_menu(), npc::handle_sound(), vehicle::handle_trap(), harvest_common(), iexamine::harvest_plant(), iexamine::harvest_ter(), iexamine::harvest_ter_nectar(), Character::has_alarm_clock(), has_clear_path_to_pickup_items(), has_neighbor(), has_pre_terrain(), Character::has_watch(), haul(), Character::heat_emission(), here(), Character::i_add_or_drop(), Character::in_climate_control(), in_spell_aoe(), advanced_inv_area::init(), vehicle::interact_with(), place_trap_actor::is_allowed(), explosion_handler::ExplosionProcess::is_occluded(), Character::is_snuggling(), is_solid_neighbor(), activity_handlers::jackhammer_do_turn(), activity_handlers::jackhammer_finish(), iexamine::keg(), iexamine::kiln_empty(), iexamine::kiln_full(), Character::knock_back_to(), monster::knock_back_to(), game::knockback(), iexamine::ledge(), explosion_handler::legacy_blast(), explosion_handler::legacy_shrapnel(), iexamine::locked_object(), iexamine::locked_object_pickable(), activity_handlers::longsalvage_finish(), mattack::longswipe(), make_active(), trapfunc::map_regen(), editmap::mapgen_preview(), editmap::mapgen_veh_destroy(), vehicle::merge_rackable_vehicle(), iexamine::migo_nerve_cluster(), activity_handlers::milk_finish(), mill_activate(), iexamine::mill_finalize(), mill_load_food(), mine_activity(), map::mop_spills(), monster::move(), npc::move(), advanced_inventory::move_all_items(), npc::move_away_from(), move_creatures_away(), veh_interact::move_cursor(), explosion_handler::ExplosionProcess::move_entity(), anonymous_namespace{iexamine_elevator.cpp}::move_item(), move_item(), move_items(), npc::move_to(), move_vehicles(), firestarter_actor::moves_cost_by_fuel(), MapExtras::mx_helicopter(), iexamine::nanofab(), nearest_passable(), iuse::note_bionics(), iexamine::on_smoke_out(), open(), vehicle::open_or_close(), activity_handlers::operation_do_turn(), activity_handlers::operation_finish(), operator_present(), activity_handlers::oxytorch_finish(), vehicle::part_collision(), vehicle::part_removal_cleanup(), Character::passive_power_gen(), iexamine::pedestal_temple(), iexamine::pedestal_wyrm(), tutorial_game::per_turn(), liquid_handler::perform_liquid_transfer(), Character::perform_uninstall(), perform_zone_activity_turn(), photo_def_for_camera_point(), pick_plant(), character_funcs::pick_safe_adjacent_tile(), pickup::pick_up(), npc::pick_up_item(), activity_handlers::pickaxe_finish(), iexamine::pit(), iexamine::pit_covered(), place_and_add_as_known(), place_construction(), Character::place_corpse(), basecamp::place_results(), activity_handlers::plant_seed_finish(), player_on_couch(), pldrive(), points_for_gas_cloud(), iexamine::portable_structure(), tutorial_game::post_action(), iexamine::pour_into_keg(), firestarter_actor::prep_firestarter_use(), game::print_terrain_info(), item::process_cable(), item::process_extinguish(), item::process_fake_mill(), item::process_fake_smoke(), map::process_fields_in_submap(), item::process_internal(), item::process_litcig(), relic_funcs::process_recharge_entry(), explosion_handler::ExplosionProcess::project_shrapnel(), projectile_attack(), spell_effect::projectile_attack(), vehicle_part::properties_to_item(), activity_handlers::pry_nails_finish(), activity_handlers::pulp_do_turn(), put_into_vehicle(), put_into_vehicle_or_drop(), iexamine::quern_examine(), plot_options::query_seed(), mattack::ranged_pull(), rcdrive(), Character::reach_attack(), npc::reach_omt_destination(), editmap::recalc_target(), iexamine::recycle_compactor(), npc::regen_ai_cache(), iexamine::reload_furniture(), avatar_action::reload_weapon(), explosion_handler::ExplosionProcess::remove_field(), remove_submap_turrets(), DefaultRemovePartHandler::removed(), requirements_map(), explosion_handler::explosion_funcs::resonance_cascade(), zone_manager::revert_vzones(), mattack::riotbot(), rod_fish(), route_adjacent(), iexamine::rubble(), explosion_handler::ExplosionProcess::run(), target_ui::run(), area_expander::run(), Character::run_cost(), mapbuffer::save(), scatter_chunks(), character_funcs::search_surroundings(), npc::see_item_say_smth(), Creature::sees(), Character::sees_with_infrared(), select_autopickup_items(), veh_interact::serialize_activity(), target_ui::set_cursor_pos(), conditional_t< T >::set_is_outside(), set_item_map_or_vehicle(), DefaultRemovePartHandler::set_transparency_cache_dirty(), editmap::setup_fmenu(), activity_handlers::shear_finish(), vehicle::shift_zlevel(), mattack::shriek_stun(), iexamine::shrub_marloss(), iexamine::shrub_wildveggies(), iexamine::sign(), sinkhole_safety_roll(), smash(), smoker_activate(), smoker_finalize(), smoker_load_food(), iexamine::smoker_options(), debug_menu::spawn_nested_mapgen(), spawn_spores(), spell_effect::spawn_summoned_vehicle(), spell_effect::spell_effect_cone(), spell_move(), mdeath::splatter(), vehicle::split_vehicles(), Character::spores(), fungal_effects::spread_fungus(), map::spread_gas(), item_stack::stacks_with(), activity_handlers::start_engines_finish(), activity_handlers::start_fire_do_turn(), game::start_game(), stash_on_pet(), vehicle::stop(), monster::stumble(), Character::suffer_from_asthma(), Character::suffer_from_other_mutations(), Character::suffer_from_radiation(), ranged::targetable_creatures(), teleport::teleport(), terrain_collision_data(), test_passable(), tidy_activity(), gates::toggle_gate(), iexamine::toPumpFuel(), vehicle::total_wind_epower_w(), iexamine::trap(), activity_handlers::travel_do_turn(), iexamine::tree_hickory(), iexamine::tree_maple(), iexamine::tree_maple_tapped(), iexamine::tree_marloss(), explosion_iuse::trigger_explosion(), try_fuel_fire(), try_remove_bear_trap(), try_remove_grab(), try_remove_heavysnare(), try_remove_lightsnare(), avatar_funcs::try_to_sleep(), turnOnSelectedPump(), iuse::unfold_generic(), unroll_digging(), editmap::update_view_with_help(), consume_drug_iuse::use(), place_npc_iuse::use(), pick_lock_actor::use(), deploy_furn_actor::use(), place_trap_actor::use(), emit_actor::use(), deploy_tent_actor::use(), unpack_actor::use(), basecamp::validate_sort_points(), vehicle_activity(), activity_handlers::vehicle_finish(), vehicle_selector::vehicle_selector(), Character::vomit(), wait(), iexamine::water_source(), iuse::weather_tool(), avatar_action::wield(), workbench_crafting_speed_multiplier(), and npc::worker_downtime().
move_creatures()
auto anonymous_namespace{iexamine_elevator.cpp}::elevator::move_creatures (const elevator::tiles from, const elevator::tiles dest) -> void
Definition at line 177 of file iexamine_elevator.cpp.
{
    for( Creature &critter : g->all_creatures() ) {
        const auto eit = std::find( from.cbegin(), from.cend(), critter.pos() );
        if( eit != from.cend() ) {
            critter.setpos( dest[ std::distance( from.cbegin(), eit ) ] );
        }
    }
}
References dest(), detail::find(), and g.
Referenced by iexamine::elevator().
move_creatures_away()
auto anonymous_namespace{iexamine_elevator.cpp}::elevator::move_creatures_away (const elevator::tiles & dest) -> void
Definition at line 140 of file iexamine_elevator.cpp.
{
    map &here = get_map();
    const auto is_movable = [&]( const tripoint & candidate ) {
        return !here.has_flag( TFLAG_ELEVATOR, candidate )
               && here.passable( candidate )
               && !g->critter_at( candidate );
    };
    for( Creature &critter : g->all_creatures() ) {
        const tripoint local_pos = here.getlocal( here.getglobal( critter.pos() ) );
        const auto eit = std::find( dest.cbegin(), dest.cend(), local_pos );
        if( eit == dest.cend() ) {
            continue;
        }
        const auto xs = closest_points_first( *eit, 10 );
        const auto candidate = std::find_if( xs.begin(), xs.end(), is_movable );
        if( candidate == xs.end() ) {
            continue;
        }
        critter.setpos( *candidate );
    }
}
References closest_points_first(), dest(), detail::find(), g, get_map(), here(), and TFLAG_ELEVATOR.
Referenced by iexamine::elevator().
move_items()
auto anonymous_namespace{iexamine_elevator.cpp}::elevator::move_items (const elevator::tiles from, const elevator::tiles dest) -> void
Definition at line 167 of file iexamine_elevator.cpp.
{
    map &here = get_map();
    for( decltype( from )::size_type i = 0; i < from.size(); i++ ) {
        const tripoint &src = from[i];
        move_item( here, src, dest[i] );
    }
}
References dest(), get_map(), here(), and move_item().
Referenced by iexamine::elevator().
move_vehicles()
auto anonymous_namespace{iexamine_elevator.cpp}::elevator::move_vehicles (const elevator_vehicles & vehs, const tripoint & sm_orig, int movez, int turns) -> void
Definition at line 187 of file iexamine_elevator.cpp.
{
    map &here = get_map();
    for( vehicle *v : vehs.v ) {
        const tripoint p = rotate_point_sm( { v->global_pos3().xy(), movez }, sm_orig, turns );
        here.displace_vehicle( *v, p - v->global_pos3() );
        v->turn( turns * 90_degrees );
        v->face = tileray( v->turn_dir );
        v->precalc_mounts( 0, v->turn_dir, v->pivot_anchor[0] );
    }
    here.reset_vehicle_cache();
}
References vehicle::face, get_map(), vehicle::global_pos3(), here(), vehicle::pivot_anchor, vehicle::precalc_mounts(), rotate_point_sm(), vehicle::turn(), and vehicle::turn_dir.
Referenced by iexamine::elevator().
vehicle_status()
auto anonymous_namespace{iexamine_elevator.cpp}::elevator::vehicle_status (const wrapped_vehicle & veh, const elevator::tiles & tiles) -> overlap_status
Definition at line 93 of file iexamine_elevator.cpp.
{
    const auto &ps = veh.v->get_all_parts();
    const int all_vparts_count = ps.part_count();
    const int vparts_inside = std::count_if( ps.begin(), ps.end(), [&]( const vpart_reference & vp ) {
        const tripoint p = veh.pos + vp.part().precalc[0];
        const auto eit = std::find( tiles.cbegin(), tiles.cend(), p );
        return eit != tiles.cend();
    } );
    if( vparts_inside == all_vparts_count ) {
        return overlap_status::inside;
    } else if( vparts_inside == 0 ) {
        return overlap_status::outside;
    } else {
        return overlap_status::overlap;
    }
}
References overlap().
Referenced by vehicles_on().
vehicles_on()
auto anonymous_namespace{iexamine_elevator.cpp}::elevator::vehicles_on (const elevator::tiles & tiles) -> elevator_vehicles
Definition at line 117 of file iexamine_elevator.cpp.
{
    const VehicleList vehs = get_map().get_vehicles();
    std::vector<vehicle *> ret;
    for( const wrapped_vehicle &veh : vehs ) {
        const auto status = vehicle_status( veh, tiles );
        if( status == overlap_status::overlap ) {
            return { true, { veh.v } };
        }
        if( status == overlap_status::inside ) {
            ret.push_back( veh.v );
        }
    }
    return { false, ret };
}
References get_map(), map::get_vehicles(), overlap(), cata::hash64_detail::ret, and vehicle_status().
Referenced by iexamine::elevator().
warn_blocking()
auto anonymous_namespace{iexamine_elevator.cpp}::elevator::warn_blocking (const elevator_vehicles & vehs, std::string_view location) -> void
Definition at line 134 of file iexamine_elevator.cpp.
{
    const auto &first_veh_name = vehs.v.front()->name;
    popup( string_format( _( "%1$s %2$s is blocking the elevator." ), first_veh_name, location ) );
}
References _, popup(), and string_format().
Referenced by iexamine::elevator().