Cataclysm BN: anonymous_namespace{iexamine_elevator.cpp} Namespace Reference
anonymous_namespace{iexamine_elevator.cpp} Namespace Reference
Namespaces
namespace elevator
Functions
auto move_item (map &here, const tripoint &src, const tripoint &dest) -> void
Function Documentation
move_item()
auto anonymous_namespace{iexamine_elevator.cpp}::move_item (map & here, const tripoint & src, const tripoint & dest) -> void
Definition at line 21 of file iexamine_elevator.cpp.
{
    map_stack items = here.i_at( src );
    for( auto it = items.begin(); it != items.end(); ) {
        here.add_item_or_charges( dest, *it );
        it = here.i_rem( src, it );
    }
};
References item_stack::begin(), anonymous_namespace{iexamine_elevator.cpp}::elevator::dest(), item_stack::end(), and anonymous_namespace{iexamine_elevator.cpp}::elevator::here().