Cataclysm BN: anonymous_namespace{mattack_actors.cpp} Namespace Reference
anonymous_namespace{mattack_actors.cpp} Namespace Reference
Functions
auto find_target_vehicle (monster &z, int range) -> std::optional< tripoint >
Function Documentation
find_target_vehicle()
auto anonymous_namespace{mattack_actors.cpp}::find_target_vehicle (monster & z, int range) -> std::optional<tripoint>
Definition at line 492 of file mattack_actors.cpp.
{
    const auto is_different_plane = []( const wrapped_vehicle & v, const monster & m ) -> bool {
        return !fov_3d && v.pos.z != m.pos().z;
    };
    map &here = get_map();
    bool found = false;
    tripoint aim_at;
    for( wrapped_vehicle &v : here.get_vehicles() ) {
        if( is_different_plane( v, z ) || v.v->velocity == 0 ) {
            continue;
        }
        bool found_controls = false;
        for( const vpart_reference &vp : v.v->get_avail_parts( "CONTROLS" ) ) {
            if( !z.sees( vp.pos() ) ) {
                continue;
            }
            int new_dist = rl_dist( z.pos(), vp.pos() );
            if( new_dist <= range ) {
                aim_at = vp.pos();
                range = new_dist;
                found = true;
                found_controls = true;
            }
        }
        if( !found_controls ) {
            std::vector<tripoint> line = here.find_clear_path( z.pos(), v.v->global_pos3() );
            tripoint prev_point = z.pos();
            for( tripoint &i : line ) {
                if( !z.sees( i ) ||  here.floor_between( prev_point, i ) ) {
                    break;
                }
                optional_vpart_position vp = here.veh_at( i );
                if( vp && &vp->vehicle() == v.v ) {
                    int new_dist = rl_dist( z.pos(), i );
                    if( new_dist <= range ) {
                        aim_at = i;
                        range = new_dist;
                        found = true;
                    }
                    break;
                }
                if( !here.is_transparent( i ) ) {
                    break;
                }
                prev_point = i;
            }
        }
    }
    if( found ) {
        return std::make_optional( aim_at );
    } else {
        return std::optional<tripoint>();
    }
}
References fov_3d, vehicle::get_avail_parts(), get_map(), vehicle::global_pos3(), anonymous_namespace{iexamine_elevator.cpp}::elevator::here(), line(), wrapped_vehicle::pos, range, rl_dist(), wrapped_vehicle::v, vehicle::velocity, and tripoint::z.
Referenced by gun_actor::call().