Cataclysm BN: src/point_rotate.h File Reference
point_rotate.h File Reference
#include "point.h"
#include "coordinates.h"
Macros
#define CATA_SRC_POINT_ROTATE_H
Functions
auto rotate (point p, point dim, int turns) -> point
Rotate point clockwise.
auto rotate (const tripoint &p, point dim, int turns) -> tripoint
Rotates just the x,y component of the tripoint.
auto rotate_point_sm (const tripoint &p, const tripoint &orig, int turns) -> tripoint
works like rotate but for submaps.
auto get_rot_turns (const tripoint_abs_omt &here, const tripoint_abs_omt &there) -> int
Macro Definition Documentation
CATA_SRC_POINT_ROTATE_H
#define CATA_SRC_POINT_ROTATE_H
Definition at line 3 of file point_rotate.h.
Function Documentation
get_rot_turns()
auto get_rot_turns (const tripoint_abs_omt & here, const tripoint_abs_omt & there) -> int
Returns
The difference in rotation between two overmap terrain points.
Definition at line 34 of file point_rotate.cpp.
{
    const auto this_dir = overmap_buffer.ter( there )->get_dir();
    const auto that_dir = overmap_buffer.ter( here )->get_dir();
    int const diff = static_cast<int>( this_dir ) - static_cast<int>( that_dir );
    return diff >= 0 ? diff : 4 + diff;
}
References oter_t::get_dir(), anonymous_namespace{iexamine_elevator.cpp}::elevator::here(), overmap_buffer, and overmapbuffer::ter().
Referenced by anonymous_namespace{iexamine_elevator.cpp}::elevator::choose_floor(), and iexamine::elevator().
rotate() [1/2]
auto rotate (const tripoint & p, point dim, int turns) -> tripoint
Rotates just the x,y component of the tripoint.
See point::rotate()
Definition at line 20 of file point_rotate.cpp.
{
    return { rotate( p.xy(), dim, turns ), p.z };
}
References rotate().
rotate() [2/2]
auto rotate (point p, point dim, int turns) -> point
Rotate point clockwise.
Parameters
turns times, 90 degrees per turn, around the center of a rectangle with the dimensions specified by
dim set dim to (0, 0) to rotate around the origin.
Definition at line 6 of file point_rotate.cpp.
{
    switch( turns ) {
        case 1:
            return { dim.y - p.y - 1, p.x };
        case 2:
            return { dim.x - p.x - 1, dim.y - p.y - 1 };
        case 3:
            return { p.y, dim.x - p.x - 1 };
        default:
            return p;
    }
}
References point::y.
Referenced by rotate(), and rotate_point_sm().
rotate_point_sm()
auto rotate_point_sm (const tripoint & p, const tripoint & orig, int turns) -> tripoint
works like rotate but for submaps.
Definition at line 25 of file point_rotate.cpp.
{
    const tripoint p_sm{ p - orig.xy() };
    const tripoint rd{ rotate( p_sm, { SEEX * 2, SEEY * 2 }, turns ) };
    return tripoint{ rd + orig.xy() };
}
References rotate(), SEEX, SEEY, and tripoint::xy().
Referenced by anonymous_namespace{iexamine_elevator.cpp}::elevator::choose_floor(), and anonymous_namespace{iexamine_elevator.cpp}::elevator::move_vehicles().